Repository AElfProject/AElf, pull requests merged in 2019-01, with the labels that each got.

#768 Fix node sync up
  AElf.Network/Peers/Peer.Sync.cs
  AElf.Node/Protocol/NetworkManager.cs
Labels: review

#770 Bug fix - Dividends Contract
  AElf.Contracts.Consensus.Tests/ConsensusElectionTest.cs
  AElf.Contracts.Consensus.Tests/ContractsShims/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/DividendsTest.cs
  AElf.Contracts.Consensus/ConsensusContract.cs
  AElf.Contracts.Consensus/Contracts/Election.cs
  AElf.Contracts.Consensus/Contracts/Process.cs
  AElf.Contracts.Consensus/README.md
  AElf.Contracts.Dividends/DividendsContract.cs
  AElf.Kernel.Types/Consensus/Miners.cs
  AElf.Kernel.Types/Consensus/Round.cs
  AElf.Kernel.Types/Consensus/TermRounds.cs
  AElf.Kernel.Types/Consensus/VotingRecord.cs
  AElf.Kernel.Types/Protobuf/Proto/consensus.proto
  AElf.Node/Consensus/DPoS.cs
  AElf.Sdk.CSharp/Api.cs
  AElf.SmartContract/SmartContractService.cs
  AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs
Labels: review

#776 Add trigger for linked situation.
  AElf.ChainController/EventMessages/BlockLinked.cs
  AElf.Node/Protocol/NetworkManager.cs
  AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs
Labels: review

#786 Feature : contract update supports proposal
  AElf.CLI2/Commands/CMDModule.cs
  AElf.CLI2/Commands/Contract/ChangeContractOwnerCommand.cs
  AElf.CLI2/Commands/Contract/DeployContractCommand.cs
  AElf.CLI2/Commands/Contract/UpdateContractCommand.cs
  AElf.CLI2/Scripts/contract.js
  AElf.Contracts.Authorization/AuthorizationContract.cs
  AElf.Contracts.CrossChain/CrossChainContract.cs
  AElf.Contracts.Genesis.Tests/ContractZeroTest.cs
  AElf.Contracts.Genesis.Tests/MockSetup.cs
  AElf.Contracts.Genesis/BasicContractZero.cs
  AElf.Sdk.CSharp/Api.cs
  AElf.SmartContract/SmartContractService.cs
Labels: review

#799 change ICallGraphStore from ICanonicalStore
  AElf.Kernel/Managers/FunctionMetadataManager.cs
Labels: review

#773 Fix net badblock handling
  AElf.ChainController/EventMessages/BlockRejected.cs
  AElf.Miner/Miner/Miner.cs
  AElf.Miner/TxMemPool/TransactionFilter.cs
  AElf.Network/Peers/Peer.cs
  AElf.Node/Consensus/DPoS.cs
  AElf.Node/Protocol/NetworkManager.cs
  AElf.Synchronization.Tests/BlockSetTests.cs
  AElf.Synchronization/AElf.Synchronization.csproj
  AElf.Synchronization/BlockExecution/BlockExecutionResult.cs
  AElf.Synchronization/BlockExecution/BlockExecutor.cs
  AElf.Synchronization/BlockSynchronization/BlockSet.cs
  AElf.Synchronization/BlockSynchronization/BlockState.cs
  AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs
Labels: review

#809 Set previous to null after lib block.
  AElf.Synchronization/BlockSynchronization/BlockSet.cs
  AElf.Synchronization/BlockSynchronization/BlockState.cs
Labels: review

#812 Fix dpos time slot problem
  AElf.Kernel.Consensus/ConsensusObserver.cs
Labels: review

#813 Fix bug unformatted signature.
  AElf.CLI2/AElf.CLI2.csproj
  AElf.Contracts.Authorization/AuthorizationContract.cs
  AElf.Cryptography/CryptoHelpers.cs
  AElf.Kernel.Types/Transaction/TxSignatureVerifier.cs
  AElf.Miner/TxMemPool/TxHub.cs
  AElf.Sdk.CSharp/Api.cs
Labels: review

#817 Sync again on higher announcement.
  AElf.Node/Protocol/NetworkManager.cs
Labels: review

#814 Feature/statemanager 20190113
  AElf.Common/HexExtensions.cs
  AElf.Kernel.Tests/BlockchainStateManagerTests.cs
  AElf.Kernel.Types/Protobuf/Proto/kernel.proto
  AElf.Kernel/KernelAElfModule.cs
  AElf.Kernel/Managers/IStateManager.cs
  AElf.Kernel/Storages/IKeyValueStore.cs
  AElf.Kernel/Storages/KeyValueStoreBase.cs
  docs/Development/architecture.md
Labels: WIP, review

#780 Add some test cases and fix other syncing problems
  AElf.Common/GlobalConfig.cs
  AElf.Configuration/Config/Database/database.json
  AElf.Contracts.Consensus.Tests/ConfigureTestFramework.cs
  AElf.Contracts.Consensus.Tests/ConsensusElectionTest.cs
  AElf.Contracts.Consensus.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.Tests/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/ContractsShims/ContractZeroShim.cs
  AElf.Contracts.Consensus.Tests/ContractsShims/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/ContractsShims/DividendsContractShim.cs
  AElf.Contracts.Consensus.Tests/ContractsShims/TokenContractShim.cs
  AElf.Contracts.Consensus.Tests/DividendsTest.cs
  AElf.Contracts.Consensus.Tests/MockSetup.cs
  AElf.Contracts.Consensus.Tests/TermTest.cs
  AElf.Contracts.Consensus/ConsensusContract.cs
  AElf.Contracts.Consensus/Contracts/DataCollection.cs
  AElf.Contracts.Consensus/Contracts/Election.cs
  AElf.Contracts.Consensus/Contracts/Process.cs
  AElf.Contracts.Consensus/README.md
  AElf.Contracts.Dividends/DividendsContract.cs
  AElf.Contracts.Dividends/README.md
  AElf.Contracts.Token/TokenContract.cs
  AElf.Kernel.Consensus/ConsensusBehavior.cs
  AElf.Kernel.Consensus/ConsensusHelper.cs
  AElf.Kernel.Consensus/ConsensusObserver.cs
  AElf.Kernel.Tests/BlockChainTests.cs
  AElf.Kernel.Tests/BlockChainTests_MockSetup.cs
  AElf.Kernel.Types/Consensus/Miners.cs
  AElf.Kernel.Types/Consensus/Round.cs
  AElf.Kernel.Types/Consensus/VotingRecord.cs
  AElf.Kernel.Types/Protobuf/Proto/consensus.proto
  AElf.Kernel.Types/Protobuf/Proto/kernel.proto
  AElf.Kernel/Managers/MinersManager.cs
  AElf.Miner/Miner/Miner.cs
  AElf.Miner/TxMemPool/TransactionFilter.cs
  AElf.Node/Consensus/DPoS.cs
  AElf.Node/Consensus/IConsensus.cs
  AElf.Node/Protocol/NetworkManager.cs
  AElf.Sdk.CSharp/Api.cs
  AElf.SmartContract/SmartContractService.cs
Labels: review

#769 Improve proposal
  AElf.Configuration/Config/Chain/chain.json
  AElf.Contracts.Authorization.Tests/AElf.Contracts.Authorization.Tests.csproj
  AElf.Contracts.Authorization/AuthorizationContract.cs
  AElf.Contracts.Genesis.Tests/ContractZeroTest.cs
  AElf.Contracts.Genesis.Tests/TestContractShim.cs
  AElf.Sdk.CSharp/Api.cs
Labels: review

#826 Replace actor config
  AElf.Concurrency.Lighthouse/AElf.Concurrency.Lighthouse.csproj
  AElf.Concurrency.Lighthouse/CliOptions.cs
  AElf.Concurrency.Lighthouse/ConfigParser.cs
  AElf.Concurrency.Lighthouse/ExecutionOptions.cs
  AElf.Concurrency.Lighthouse/LighthouseConcurrencyAElfModule.cs
  AElf.Concurrency.Lighthouse/ManagementService.cs
  AElf.Concurrency.Lighthouse/Program.cs
  AElf.Concurrency.Lighthouse/akka-lighthouse.hocon
  AElf.Concurrency.Lighthouse/appsettings.Development.json
  AElf.Concurrency.Lighthouse/appsettings.json
  AElf.Concurrency.Worker/ActorEnvironment.cs
  AElf.Concurrency.Worker/CliOptions.cs
  AElf.Concurrency.Worker/ConfigParser.cs
  AElf.Concurrency.Worker/Program.cs
  AElf.Concurrency.Worker/WorkerConcurrencyAElfModule.cs
  AElf.Concurrency.Worker/akka-worker.hocon
  AElf.Concurrency.Worker/appsettings.Development.json
  AElf.Concurrency.Worker/appsettings.json
  AElf.Configuration/AElf.Configuration.csproj
  AElf.Configuration/CommandLineParser.cs
  AElf.Configuration/Config/Executor/ActorConfig.cs
  AElf.Configuration/Config/Executor/actor.json
  AElf.Configuration/Config/Node/transaction-pool.json
  AElf.Execution/AElf.Execution.csproj
  AElf.Execution/ActorEnvironment.cs
  AElf.Execution/ExecutionAElfModule.cs
  AElf.Execution/ExecutionOptions.cs
  AElf.Execution/NoFeeParallelTransactionExecutingService.cs
  AElf.Execution/ParallelTransactionExecutingService.cs
  AElf.Execution/akka-master.hocon
  AElf.Execution/akka-single.hocon
  AElf.Kernel.Tests/Concurrency/ParallelTransactionExecutingServiceTest.cs
  AElf.Kernel.Tests/KernelTestAElfModule.cs
  AElf.Launcher/appsettings.json
  AElf.Management/Services/WorkerService.cs
  AElf.Monitor/AElf.Monitor.csproj
  AElf.Monitor/Akka/AkkaModule.cs
  AElf.Monitor/AkkaService.cs
  AElf.Monitor/ExecutionOptions.cs
  AElf.Monitor/Program.cs
  AElf.Monitor/Startup.cs
  AElf.Monitor/akka-monitor.hocon
  AElf.Monitor/appsettings.Development.json
  AElf.Monitor/appsettings.json
  AElf.Network/Peers/PeerManager.cs
Labels: Mergeable, review

#844 Fixed SmartContractService injection in tests
  AElf.Contracts.Authorization.Tests/AuthorizationContractShim.cs
  AElf.Contracts.Authorization.Tests/MockSetup.cs
  AElf.Contracts.Genesis.Tests/MockSetup.cs
  AElf.Contracts.SideChain.Tests/MockSetup.cs
  AElf.Kernel.Tests/BlockChainTests_MockSetup.cs
  AElf.Kernel.Tests/Concurrency/Execution/MockSetup.cs
  AElf.Kernel/Managers/IStateManager.cs
  AElf.Miner.Tests/MinerTestAElfModule.cs
  AElf.Miner.Tests/MockSetup.cs
  AElf.Runtime.CSharp.Tests/MockSetup.cs
  AElf.Runtime.CSharp/Executive.cs
  AElf.Runtime.CSharp2.Tests/AElf.Runtime.CSharp2.Tests.csproj
  AElf.Runtime.CSharp2.Tests/MockStateProvider.cs
  AElf.Runtime.CSharp2.Tests/MockStateProviderFactory.cs
  AElf.Runtime.CSharp2.Tests/TestCSharpRuntimeAElfModule.cs
  AElf.Runtime.CSharp2.Tests/TestContractShim.cs
  AElf.Runtime.CSharp2/AElf.Runtime.CSharp2.csproj
  AElf.Runtime.CSharp2/CSharpSmartContractProxy.cs
  AElf.Runtime.CSharp2/Executive2.cs
  AElf.Sdk.CSharp.Tests/MockSetup.cs
  AElf.Sdk.CSharp2.Tests/ContractTest.cs
  AElf.Sdk.CSharp2.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp2.Tests/MockStateProviderFactory.cs
  AElf.Sdk.CSharp2.Tests/StateTest.cs
  AElf.Sdk.CSharp2/CSharpSmartContractAbstract.cs
  AElf.Sdk.CSharp2/CSharpSmartContract`_Internal.cs
  AElf.Sdk.CSharp2/Properties/InternalVisibleTo.cs
  AElf.Sdk.CSharp2/State/MappedState.cs
  AElf.Sdk.CSharp2/State/SingletonState`.cs
  AElf.Sdk.CSharp2/State/StateBase.cs
  AElf.Sdk.CSharp2/State/StructuredState.cs
  AElf.SmartContract/Contexts/IExecutive.cs
  AElf.SmartContract/Contexts/IStateProvider.cs
  AElf.SmartContract/Contexts/IStateProviderFactory.cs
  AElf.SmartContract/Contexts/StateProvider.cs
  AElf.SmartContract/Contexts/StateProviderFactory.cs
  AElf.SmartContract/SmartContractService.cs
Labels: Mergeable, review

#845 Add events for resource and make it available in rpc
  AElf.ChainController.Rpc/ChainControllerRpcService.cs
  AElf.Contracts.Resource/BancorHelpers.cs
  AElf.Contracts.Resource/ResourceContract.cs
  AElf.Contracts.Token/TokenContract.cs
  AElf.Sdk.CSharp/Event.cs
Labels: Mergeable, review

#835 Replace configuration
  AElf.ChainController/BlockValidation/Filters/ConsensusValidationFilter.cs
  AElf.ChainController/ChainAElfModule.cs
  AElf.Configuration/AElf.Configuration.csproj
  AElf.Configuration/CommandLineParser.cs
  AElf.Configuration/Config/Node/NodeConfig.cs
  AElf.Configuration/Config/Node/node.json
  AElf.Cryptography/AElfKeyStore.cs
  AElf.Cryptography/IKeyStore.cs
  AElf.Execution/ExecutionAElfModule.cs
  AElf.Execution/ExecutionOptions.cs
  AElf.Execution/ParallelTransactionExecutingService.cs
  AElf.Kernel.Consensus/ConsensusDataProvider.cs
  AElf.Kernel.Consensus/ConsensusKernelAElfModule.cs
  AElf.Kernel.Consensus/ConsensusObserver.cs
  AElf.Kernel.Tests/KernelTestAElfModule.cs
  AElf.Kernel/Account/IAccountService.cs
  AElf.Kernel/Extensions/BlockExtensions.cs
  AElf.Launcher/AElf.Launcher.csproj
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Launcher/appsettings.json
  AElf.Miner.Tests/MinerLifetimeTests.cs
  AElf.Miner.Tests/MinerTestAElfModule.cs
  AElf.Miner.Tests/MockSetup.cs
  AElf.Miner/Miner/Miner.cs
  AElf.Miner/MinerAElfModule.cs
  AElf.Miner/TxMemPool/TransactionFilter.cs
  AElf.Network.Tests/AElf.Network.Tests.csproj
  AElf.Network.Tests/NetworkTestBase.cs
  AElf.Network.Tests/PeerSyncTest.cs
  AElf.Network.Tests/PeerTests.cs
  AElf.Network.Tests/TestsNetworkAElfModule.cs
  AElf.Network/Peers/Peer.cs
  AElf.Network/Peers/PeerManager.cs
  AElf.Node/AElfChain/MainchainNodeService.cs
  AElf.Node/Consensus/DPoS.cs
  AElf.Node/NodeAElfModule.cs
  AElf.Node/NodeConfiguration.cs
  AElf.OS.Tests/AElf.OS.Tests.csproj
  AElf.OS.Tests/Account/AccountServiceTests.cs
  AElf.OS.Tests/OSTestBase.cs
  AElf.OS.Tests/TestsOSAElfModule.cs
  AElf.OS.Tests/UnitTest1.cs
  AElf.OS/AElf.OS.csproj
  AElf.OS/AElfOSModule.cs
  AElf.OS/Account/AccountService.cs
  AElf.OS/AccountOptions.cs
  AElf.RPC.Tests/TestsRpcAElfModule.cs
  AElf.Runtime.CSharp.Tests/TestCSharpRuntimeAElfModule.cs
  AElf.Runtime.CSharp2.Tests/TestCSharpRuntimeAElfModule.cs
  AElf.SideChain.Creation/ChainCreationEventListener.cs
  AElf.SideChain.Creation/DeployOptions.cs
  AElf.SideChain.Creation/SideChainAElfModule.cs
  AElf.Synchronization/BlockExecution/BlockExecutor.cs
  AElf.Synchronization/BlockSynchronization/BlockSynchronizer.cs
Labels: Mergeable, review

#842 Feature/chain manager 20190120
  AElf.Kernel.Tests/ChainManagerTests.cs
  AElf.Kernel/KernelAElfModule.cs
  AElf.Kernel/Managers/ISecondChainManager.cs
  AElf.Types/Hash.cs
  AElf.Types/Protobuf/Proto/kernel.proto
Labels: Mergeable, review

#849 Fix/contract serial number problem
  AElf.Common/GlobalConfig.cs
  AElf.Contracts.Genesis/BasicContractZero.cs
Labels: Mergeable

#852 Fix/data confusion between contracts
  AElf.Sdk.CSharp/Types/Map.cs
  AElf.SmartContract/SmartContractService.cs
Labels: review

#854 Fix/wrong signature verification methods
  AElf.Contracts.Authorization.Tests/AuthorizationContractShim.cs
  AElf.Contracts.Authorization.Tests/AuthorizationTest.cs
  AElf.Contracts.Consensus.Tests/ConsensusElectionTest.cs
  AElf.Contracts.Consensus.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.Tests/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/DividendsTest.cs
  AElf.Contracts.Consensus.Tests/TermTest.cs
  AElf.Cryptography.Tests/CryptoHelpersTests.cs
  AElf.Cryptography.Tests/ECDSA/BlockSignatureTest.cs
  AElf.Cryptography.Tests/ECDSA/EcdsaTest.cs
  AElf.Cryptography/AElfKeyStore.cs
  AElf.Cryptography/CryptoHelpers.cs
  AElf.Cryptography/ECDSA/ECSignature.cs
  AElf.Cryptography/ECDSA/ECSigner.cs
  AElf.Cryptography/ECDSA/ECVerifier.cs
  AElf.Cryptography/ECDSA/KeyPairGenerator.cs
  AElf.Kernel.Tests/AddressTest.cs
  AElf.Kernel.Tests/BlockChainTests.cs
  AElf.Kernel.Tests/TransactionManagerTests.cs
  AElf.Kernel/Account/IAccountService.cs
  AElf.Kernel/Extensions/BlockHeaderExtensions.cs
  AElf.Kernel/Extensions/TransactionExtensions.cs
  AElf.Miner.Tests/MinerLifetimeTests.cs
  AElf.Miner.Tests/MinerTestAElfModule.cs
  AElf.Network.Tests/NetworkTestHelpers.cs
  AElf.Network.Tests/TestsNetworkAElfModule.cs
  AElf.Network/Peers/Peer.cs
  AElf.OS.Tests/Account/AccountServiceTests.cs
  AElf.OS.Tests/TestsOSAElfModule.cs
  AElf.OS/Account/AccountService.cs
  AElf.RPC.Tests/TestsRpcAElfModule.cs
  AElf.Wallet.Rpc/WalletRpcService.cs
Labels: review

#855 Improve read/write db performance
  AElf.Database/RedisDatabase.cs
  AElf.Database/RedisProtocol/PooledRedisLite.cs
  AElf.Database/RedisProtocol/RedisLite.cs
Labels: review

#858 Fix rpc get wrong chain id issue
  AElf.Types/Extensions/HexExtensions.cs
Labels: review
