Repository AElfProject/AElf, pull requests merged in 2019-02, with the labels that each got.

#861 Fix incorrect inline transaction execution
  AElf.SmartContract/Contexts/DataProvider.cs
Labels: Mergeable, review

#859 Refactor/Replace the hash type chain id
  AElf.Benchmark/BenchmarkTps.cs
  AElf.Contracts.Consensus.Tests/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/MockSetup.cs
  AElf.Contracts.CrossChain/CrossChainContract.cs
  AElf.Contracts.Genesis.Tests/MockSetup.cs
  AElf.Contracts.SideChain.Tests/SideChainTest.cs
  AElf.Contracts.Token.Tests/MockSetup.cs
  AElf.Kernel.Tests/BlockChainTests_MockSetup.cs
  AElf.Kernel.Tests/BlockSyncTests/BlockSyncHelpers.cs
  AElf.Kernel.Tests/BlockTest.cs
  AElf.Kernel.Tests/ChainCreationServiceTests.cs
  AElf.Kernel.Tests/ChainTest.cs
  AElf.Kernel.Tests/Concurrency/Execution/MockSetup.cs
  AElf.Kernel.Tests/Concurrency/Metadata/ChainFunctionMetadataTest.cs
  AElf.Kernel.Tests/Concurrency/Metadata/FunctionMetadataServiceTest.cs
  AElf.Kernel.Tests/Concurrency/Scheduling/GrouperTest.cs
  AElf.Kernel.Tests/DataProviderTest.cs
  AElf.Kernel.Tests/SmartContractExecuting/ContractTest.cs
  AElf.Kernel.Types/Block/IBlockInfo.cs
  AElf.Kernel.Types/ChainHelpers.cs
  AElf.Kernel/Managers/IMinersManager.cs
  AElf.Kernel/Managers/MinersManager.cs
  AElf.Miner.Tests/HeaderInfo/HeaderInfoTest.cs
  AElf.Miner.Tests/MinerLifetimeTests.cs
  AElf.Miner.Tests/MockSetup.cs
  AElf.Node/Consensus/DPoS.cs
  AElf.Runtime.CSharp.Tests/MockSetup.cs
  AElf.Runtime.CSharp2.Tests/MockSetup.cs
  AElf.Runtime.CSharp2.Tests/TestContractShim.cs
  AElf.Sdk.CSharp.Tests/MockSetup.cs
  AElf.Synchronization.Tests/SyncTestHelpers.cs
  AElf.Types/Hash.cs
  AElf.Types/Protobuf/Proto/crosschain.proto
Labels: Mergeable

#857 Feature/new blockchain service
  AElf.ChainController/ChainContextService.cs
  AElf.Kernel.Tests/BlockchainServiceTests.cs
  AElf.Kernel.Tests/BlockchainStateManagerTests.cs
  AElf.Kernel.Tests/ChainCreationServiceTests.cs
  AElf.Kernel.Tests/ChainManagerTests.cs
  AElf.Kernel.Types/SmartContract/SmartContractRegistration.cs
  AElf.Kernel/AElf.Kernel.csproj
  AElf.Kernel/Events/BestChainFoundEvent.cs
  AElf.Kernel/Managers/BinaryMerkleTreeManager.cs
  AElf.Kernel/Managers/ChainManager.cs
  AElf.Kernel/Managers/FunctionMetadataManager.cs
  AElf.Kernel/Managers/ISecondChainManager.cs
  AElf.Kernel/Managers/IStateManager.cs
  AElf.Kernel/Services/IBlockExecutingService.cs
  AElf.Kernel/Services/IBlockGenerationService.cs
  AElf.Kernel/Services/IBlockchainService.cs
  AElf.Kernel/Services/ILightBlockchainService.cs
  AElf.Kernel/Storages/StorageKeyExtensions.cs
  AElf.OS/AElf.OS.csproj
  AElf.OS/Jobs/AddBlockJob.cs
  AElf.SmartContract/Contexts/StateProvider.cs
  AElf.Types/Extensions/HexExtensions.cs
  protobuf/kernel.proto
Labels: Mergeable, review

#838 Refactor/network
  AElf.Launcher/AElf.Launcher.csproj
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Network.Tests/NetworkManagerTests/ForkSyncTests.cs
  AElf.Network.Tests/NetworkManagerTests/NetworkManagerSyncTests.cs
  AElf.Node/AElf.Node.csproj
  AElf.Node/Protocol/Job.cs
  AElf.Node/Protocol/NetworkManager.cs
  AElf.Node/Protocol/PendingRequest.cs
  AElf.OS.Network.Grpc/AElf.OS.Network.Grpc.csproj
  AElf.OS.Network.Grpc/Events/PeerDcEventArgs.cs
  AElf.OS.Network.Grpc/Generated/.gitkeep
  AElf.OS.Network.Grpc/GrpcNetworkModule.cs
  AElf.OS.Network.Grpc/GrpcNetworkServer.cs
  AElf.OS.Network.Grpc/GrpcNetworkService.cs
  AElf.OS.Network.Grpc/GrpcPeer.cs
  AElf.OS.Network.Grpc/GrpcPeerService.cs
  AElf.OS.Network.Grpc/GrpcUrl.cs
  AElf.OS.Network.Grpc/IAElfNetworkServer.cs
  AElf.OS.Network.Grpc/IPeerAuthentificator.cs
  AElf.OS.Network.Grpc/grpc.sh
  AElf.OS.Tests/AElf.OS.Tests.csproj
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS.Tests/Network/NetTestAElfModule.cs
  AElf.OS.Tests/Network/NetTestBase.cs
  AElf.OS/AElf.OS.csproj
  AElf.OS/AElfOSModule.cs
  AElf.OS/Network/Events/AnnoucementReceivedEventData.cs
  AElf.OS/Network/Events/TxReceivedEventData.cs
  AElf.OS/Network/INetworkService.cs
  AElf.OS/Network/IPeerNode.cs
  AElf.OS/Network/IPeerNodeInfo.cs
  AElf.OS/Network/IPeerNodeManager.cs
  AElf.OS/Network/IPeerToPeerManager.cs
  AElf.OS/Network/NetworkOptions.cs
  AElf.OS/Network/Temp/IBlockService.cs
  AElf.Synchronization.Tests/AElf.Synchronization.Tests.csproj
  AElf.Synchronization.Tests/BlockSetTests.cs
  AElf.Synchronization.Tests/SyncTestHelpers.cs
  AElf.Test.Helpers/AElf.Test.Helpers.csproj
  AElf.Test.Helpers/ChainGenerationHelpers.cs
  AElf.sln
  protobuf/peer_service.proto
Labels: WIP, review

#866 Initial network design reorg
  AElf.OS.Network.Grpc/GrpcNetworkModule.cs
  AElf.OS.Network.Grpc/GrpcNetworkServer.cs
  AElf.OS.Network.Grpc/GrpcNetworkService.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Network.Grpc/IAElfNetworkServer.cs
  AElf.OS.Network.Grpc/IAElfServerService.cs
  AElf.OS.Network.Grpc/IPeerAuthentificator.cs
  AElf.OS.Network.Grpc/IPeerPool.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS/AElfOSModule.cs
  AElf.OS/Network/NetworkConsts.cs
  AElf.OS/Network/NetworkOptions.cs
Labels: review

#870 Implement block executing service
  AElf.Execution/Execution/BlockExecutingService.cs
  AElf.Execution/Execution/ITransactionExecutingService.cs
  AElf.Execution/ITransactionExecutingService.cs
  AElf.Execution/TransactionExecutingService.cs
  AElf.Kernel/Services/IBlockExecutingService.cs
  protobuf/kernel.proto
Labels: Mergeable, review

#873 DPoS consensus contract converted to use sdk2
  AElf.Contracts.Consensus.DPoS2/AElf.Contracts.Consensus.DPoS2.csproj
  AElf.Contracts.Consensus.DPoS2/Config.cs
  AElf.Contracts.Consensus.DPoS2/Contract_Consensus.cs
  AElf.Contracts.Consensus.DPoS2/Contract_Election_Helper.cs
  AElf.Contracts.Consensus.DPoS2/Contract_Helpers.cs
  AElf.Contracts.Consensus.DPoS2/Contract_Process.cs
  AElf.Contracts.Consensus.DPoS2/Contract_Process_Helper.cs
  AElf.Contracts.Consensus.DPoS2/DPoSContractState.cs
  AElf.Contracts.Consensus.DPoS2/IMessageExtensions.cs
  AElf.Sdk.CSharp2/Context.cs
  AElf.Sdk.CSharp2/IContext.cs
  AElf.sln
Labels: WIP, review

#875 Add Initialize method to assign referenced contract address
  AElf.Contracts.Consensus.DPoS2/Contract_Consensus.cs
  AElf.Contracts.Consensus.DPoS2/DPoSContractState.cs
Labels: Mergeable, review

#871 Improvements to peer management
  AElf.OS.Network.Grpc/GrpcPeer.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Network.Grpc/IPeerPool.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS.Tests/Network/GrpcPeerPoolTests.cs
  AElf.OS.Tests/Network/NetMockHelpers.cs
  protobuf/peer_service.proto
Labels: review

#880 Support readonly function call in sdk2
  AElf.Runtime.CSharp2.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp2.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp2/Exceptions.cs
  AElf.Sdk.CSharp2/State/ContractReferenceState.cs
  AElf.Sdk.CSharp2/State/FuncExtensions.cs
  AElf.Sdk.CSharp2/State/FuncInfo.cs
  AElf.SmartContract/Contexts/IStateProvider.cs
  AElf.SmartContract/Contexts/StateProvider.cs
  AElf.Types.CSharp/ConversionExtension.cs
Labels: Mergeable, review

#869 Enhancement/RPC format
  AElf.ChainController.Rpc.Tests/ChainControllerRpcServiceTest.cs
  AElf.ChainController.Rpc/AElf.ChainController.Rpc.csproj
  AElf.ChainController.Rpc/ChainControllerRpcService.cs
  AElf.ChainController.Rpc/ChainRpcErrorConsts.cs
  AElf.ChainController.Rpc/DtoExtensions.cs
  AElf.ChainController.Rpc/ITransactionResultService.cs
  AElf.ChainController.Rpc/RpcChainControllerAElfModule.cs
  AElf.ChainController.Rpc/ServiceExtensions.cs
  AElf.ChainController.Rpc/TransactionResultService.cs
  AElf.Concurrency.Lighthouse/AElf.Concurrency.Lighthouse.csproj
  AElf.Management/Interfaces/INetworkService.cs
  AElf.Management/Services/AkkaService.cs
  AElf.Management/Services/NetworkService.cs
  AElf.Management/Services/NodeService.cs
  AElf.Management/Services/TransactionService.cs
  AElf.Miner.Rpc/AElf.Miner.Rpc.csproj
  AElf.Monitor/AElf.Monitor.csproj
  AElf.Monitor/AkkaService.cs
  AElf.Net.Rpc/AElf.Net.Rpc.csproj
  AElf.Net.Rpc/NetRpcAElfModule.cs
  AElf.Net.Rpc/NetRpcErrorConsts.cs
  AElf.Net.Rpc/NetRpcService.cs
  AElf.Network/AElf.Network.csproj
  AElf.Network/Peers/Peer.cs
  AElf.Network/Peers/PeerManager.cs
  AElf.OS.Network.Grpc/AElf.OS.Network.Grpc.csproj
  AElf.OS/AElf.OS.csproj
  AElf.RPC/AElf.RPC.csproj
  AElf.RPC/Hubs/Net/NetContext.cs
  AElf.RPC/Hubs/Net/NetworkHub.cs
  AElf.RPC/PathAttribute.cs
  AElf.RPC/RpcAElfModule.cs
  AElf.RPC/RpcServerHelpers.cs
  AElf.Wallet.Rpc/AElf.Wallet.Rpc.csproj
  AElf.Wallet.Rpc/RpcWalletAElfModule.cs
  AElf.Wallet.Rpc/WalletRpcErrorConsts.cs
  AElf.Wallet.Rpc/WalletRpcService.cs
Labels: WIP, review

#872 Improvement of unit test cases
  AElf.Contracts.Token2/TokenContract_Actions.cs
  AElf.Kernel.Tests/Managers/BlockManagerTests.cs
  AElf.Kernel.Tests/Managers/ChainManagerTests.cs
  AElf.Kernel.Tests/Managers/MinersManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionReceiptManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.Runtime.CSharp.Core/AElf.Runtime.CSharp.Core.csproj
  AElf.Runtime.CSharp2/AElf.Runtime.CSharp2.csproj
  AElf.Sdk.CSharp2.Tests.TestContract/TokenContract_Actions.cs
  AElf.Sdk.CSharp2.Tests/AElf.Sdk.CSharp2.Tests.csproj
  AElf.Sdk.CSharp2.Tests/ContractTest.cs
Labels: review

#883 Reorg/contract use the new SDK
  AElf.Benchmark.TestContract2/AElf.Benchmark.TestContract2.csproj
  AElf.Benchmark.TestContract2/TestTokenContract.cs
  AElf.Benchmark.TestContract2/TestTokenContractState.cs
  AElf.Contracts.Genesis2/AElf.Contracts.Genesis2.csproj
  AElf.Contracts.Genesis2/BasicContractZero.cs
  AElf.Contracts.Genesis2/BasicContractZeroHelper.cs
  AElf.Contracts.Genesis2/BasicContractZeroState.cs
  AElf.Contracts.Genesis2/Events.cs
  AElf.Contracts.Genesis2/Protobuf/Generated/.gitkeep
  AElf.Contracts.Resource.FeeReceiver2/AElf.Contracts.Resource.FeeReceiver2.csproj
  AElf.Contracts.Resource.FeeReceiver2/FeeReceiverContract.cs
  AElf.Contracts.Resource.FeeReceiver2/FeeReceiverContractState.cs
  AElf.Contracts.Resource2/AElf.Contracts.Resource2.csproj
  AElf.Contracts.Resource2/BancorHelpers.cs
  AElf.Contracts.Resource2/Events.cs
  AElf.Contracts.Resource2/Protobuf/Generated/.gitkeep
  AElf.Contracts.Resource2/Protobuf/UserResourceKey.cs
  AElf.Contracts.Resource2/ResourceContract.cs
  AElf.Contracts.Resource2/ResourceContractHelper.cs
  AElf.Contracts.Resource2/ResourceContractState.cs
  AElf.Sdk.CSharp2/Context.cs
  AElf.Sdk.CSharp2/IContext.cs
  AElf.sln
Labels: Mergeable, review

#890 Remove AElf.Benchmark related projects & fix reference for AElf.Kerne…
  AElf.Kernel.Consensus.DPoS/AElf.Kernel.Consensus.DPoS.csproj
  AElf.sln
Labels: review

#881 Convert crosschain contract to use sdk2
  AElf.Contracts.Authorization2/AElf.Contracts.Authorization2.csproj
  AElf.Contracts.Authorization2/AuthorizationContract.cs
  AElf.Contracts.Authorization2/AuthorizationContractState.cs
  AElf.Contracts.Authorization2/AuthorizationContract_Helper.cs
  AElf.Contracts.Authorization2/IMessageExtensions.cs
  AElf.Contracts.Authorization2/TimerHelper.cs
  AElf.Contracts.CrossChain2/AElf.Contracts.CrossChain2.csproj
  AElf.Contracts.CrossChain2/CrossChainContract.cs
  AElf.Contracts.CrossChain2/CrossChainContractState.cs
  AElf.Contracts.CrossChain2/CrossChainContract_Helper.cs
  AElf.Contracts.CrossChain2/Events.cs
  AElf.Contracts.CrossChain2/IMessageExtensions.cs
  AElf.Contracts.Dividends2/AElf.Contracts.Dividends2.csproj
  AElf.Contracts.Dividends2/DividendsContract.cs
  AElf.Contracts.Dividends2/DividendsContractState.cs
  AElf.Runtime.CSharp2.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp2.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp2/Context.cs
  AElf.Sdk.CSharp2/Exceptions.cs
  AElf.Sdk.CSharp2/IContext.cs
  AElf.Sdk.CSharp2/State/ContractReferenceState.cs
  AElf.Sdk.CSharp2/State/FuncExtensions.cs
  AElf.Sdk.CSharp2/State/FuncInfo.cs
  AElf.SmartContract/Contexts/IStateProvider.cs
  AElf.SmartContract/Contexts/StateProvider.cs
  AElf.Types.CSharp/ConversionExtension.cs
  AElf.sln
Labels: review

#894 Include AElf.Launcher project
  AElf.Launcher/AElf.Launcher.csproj
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Launcher/Program.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.sln
Labels: review

#882 Feature sync
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Handlers/TxReceivedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Core/Jobs/ForkDownloadJobArgs.cs
  AElf.OS.Core/Network/Events/AnnoucementReceivedEventData.cs
  AElf.OS.Core/Network/Events/PeerConnectedEventData.cs
  AElf.OS.Core/Network/INetworkService.cs
  AElf.OS.Core/Network/NetworkConsts.cs
  AElf.OS.Network.Grpc/GrpcNetworkServer.cs
  AElf.OS.Network.Grpc/GrpcNetworkService.cs
  AElf.OS.Network.Grpc/GrpcPeer.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Network.Grpc/IAElfNetworkServer.cs
  AElf.OS.Tests/AElf.OS.Tests.csproj
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS.Tests/Network/GrpcPeerPoolTests.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
  AElf.OS.Tests/Network/Sync/Unit/PeerConnectedEventHandlerTests.cs
  AElf.OS.Tests/TestsOSAElfModule.cs
  AElf.OS/Network/Events/PeerConnectedEventData.cs
  AElf.OS/Network/Handler/BlockAnnouncementEventHandler.cs
  AElf.OS/Network/Handler/TxReceivedEventHandler.cs
  AElf.OS/Network/Jobs/ForkDownloadJob.cs
  AElf.OS/Network/Jobs/ForkDownloadJobArgs.cs
  protobuf/peer_service.proto
Labels: review

#897 Enhancement/miner service
  AElf.Contracts.Consensus.DPoS/Contract_Consensus.cs
  AElf.Contracts.Consensus.DPoS/Contract_Helpers.cs
  AElf.Contracts.Consensus.DPoS/Contract_Process_Helper.cs
  AElf.Contracts.Consensus.DPoS/DPoSContractState.cs
  AElf.Kernel.ChainController/Application/ChainCreationService.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsensusModule.cs
  AElf.Kernel.Consensus.DPoS/Infrastructure/DPoSObserver.cs
  AElf.Kernel.Consensus/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Consensus/Application/ConsensusService.cs
  AElf.Kernel.Consensus/Application/ConsensusTransactionGenerator.cs
  AElf.Kernel.Consensus/Application/IConsensusObserver.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockGenerationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Blockchain/Domain/ISecondChainManager.cs
  AElf.Kernel.Core/Miner/Application/BlockMiningEventData.cs
  AElf.Kernel.Core/Miner/Application/IMinerService.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel/Services/IBlockGenerationService.cs
  AElf.Kernel/Services/IConsensusService.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Node/AElf.Node.csproj
  AElf.Node/AElfChain/MainchainNodeService.cs
  AElf.Node/Consensus/DPoS.cs
  AElf.Node/NodeAElfModule.cs
  AElf.Sdk.CSharp2/IConsensusSmartContract.cs
Labels: Mergeable, review

#901 Include RPC projects
  AElf.Net.Rpc/AElf.Net.Rpc.csproj
  AElf.Net.Rpc/NetRpcAElfModule.cs
  AElf.Net.Rpc/NetRpcService.cs
  AElf.OS.Core/Network/INetworkService.cs
  AElf.OS.Network.Grpc/GrpcNetworkService.cs
  AElf.RPC.Tests/AElf.RPC.Tests.csproj
  AElf.RPC.Tests/RpcTestBase.cs
  AElf.RPC.Tests/RpcTestStartup.cs
  AElf.RPC.Tests/TestsRpcAElfModule.cs
  AElf.RPC/AElf.RPC.csproj
  AElf.RPC/RpcAElfModule.cs
  AElf.RPC/RpcServerHelpers.cs
  AElf.Wallet.Rpc/AElf.Wallet.Rpc.csproj
  AElf.Wallet.Rpc/WalletRpcService.cs
  AElf.sln
Labels: review

#903 Feature/ci code coverage
  .travis.yml
  AElf.CLI.Tests/AElf.CLI.Tests.csproj
  AElf.ChainController.Rpc.Tests/AElf.ChainController.Rpc.Tests.csproj
  AElf.Contracts.Authorization.Tests/AElf.Contracts.Authorization.Tests.csproj
  AElf.Contracts.Consensus.DPoS.Tests/AElf.Contracts.Consensus.DPoS.Tests.csproj
  AElf.Contracts.Consensus.Tests/AElf.Contracts.Consensus.Tests.csproj
  AElf.Contracts.Genesis.Tests/AElf.Contracts.Genesis.Tests.csproj
  AElf.Contracts.SideChain.Tests/AElf.Contracts.SideChain.Tests.csproj
  AElf.Contracts.Token.Tests/AElf.Contracts.Token.Tests.csproj
  AElf.Cryptography.Tests/AElf.Cryptography.Tests.csproj
  AElf.Database.Tests/AElf.Database.Tests.csproj
  AElf.Kernel.ChainController.Tests/AElf.Kernel.ChainController.Tests.csproj
  AElf.Kernel.Consensus.DPoS.Tests/AElf.Kernel.Consensus.DPoS.Tests.csproj
  AElf.Kernel.Node.Tests/AElf.Kernel.Node.Tests.csproj
  AElf.Kernel.SmartContractExecution.Akka.Tests/AElf.Kernel.SmartContractExecution.Akka.Tests.csproj
  AElf.Kernel.SmartContractExecution.Tests/AElf.Kernel.SmartContractExecution.Tests.csproj
  AElf.Kernel.Tests/AElf.Kernel.Tests.csproj
  AElf.Kernel.TransactionPool.Tests/AElf.Kernel.TransactionPool.Tests.csproj
  AElf.Kernel.Types.Tests/AElf.Kernel.Types.Tests.csproj
  AElf.OS.Tests/AElf.OS.Tests.csproj
  AElf.RPC.Tests/AElf.RPC.Tests.csproj
  AElf.Runtime.CSharp2.Tests/AElf.Runtime.CSharp2.Tests.csproj
  AElf.Sdk.CSharp2.Tests/AElf.Sdk.CSharp2.Tests.csproj
  AElf.Test.Helpers/AElf.Test.Helpers.csproj
  AElf.Types.CSharp.Tests/AElf.Types.CSharp.Tests.csproj
  AElf.Types.Tests/AElf.Types.Tests.csproj
  scripts/build.sh
Labels: review

#893 Refactor unit test cases
  AElf.Cryptography.Tests/AElf.Cryptography.Tests.csproj
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Cryptography.Tests/CryptoHelpersTests.cs
  AElf.Cryptography/AElfKeyStore.cs
  AElf.Kernel.Types.Tests/AElf.Kernel.Types.Tests.csproj
  AElf.Kernel.Types.Tests/Block/BlockTests.cs
  AElf.Kernel.Types.Tests/BlockTest.cs
  AElf.Kernel.Types.Tests/BloomTests.cs
  AElf.Kernel.Types.Tests/ChainCreationServiceTests.cs
  AElf.Kernel.Types.Tests/ChainHelpersTests.cs
  AElf.Kernel.Types.Tests/ChainTest.cs
  AElf.Kernel.Types.Tests/Merkle/MerkleTests.cs
  AElf.Kernel.Types.Tests/SerializationTest.cs
  AElf.Kernel.Types.Tests/SerializationTests.cs
  AElf.Types.Tests/AElf.Types.Tests.csproj
  AElf.Types.Tests/AddressTest.cs
  AElf.Types.Tests/Base58Tests.cs
  AElf.Types.Tests/Extensions/ExtensionTests.cs
  AElf.Types.Tests/HashTests.cs
  AElf.Types.Tests/Helpers/ByteArrayHelpersTests.cs
  AElf.Types.Tests/Helpers/ByteStringHelpersTests.cs
  AElf.Types/Extensions/StringExtensions.cs
Labels: WIP, review

#905 Change chainId related extensions to helper
  AElf.Common/GlobalConfig.cs
  AElf.Kernel.Consensus/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Core/Domain/MinersManager.cs
  AElf.Kernel.Core/Extensions/MinerExtensions.cs
  AElf.Kernel.SmartContract/MetaData/ChainFunctionMetadata.cs
  AElf.Kernel.SmartContract/MetaData/FunctionMetadataService.cs
  AElf.Kernel.SmartContractExecution/Scheduling/Grouper.cs
  AElf.Kernel.Types.Tests/ChainHelpersTests.cs
  AElf.Kernel.Types/ChainHelpers.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Handlers/TxReceivedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS.Tests/Network/GrpcPeerPoolTests.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
  AElf.OS.Tests/Network/Sync/Unit/PeerConnectedEventHandlerTests.cs
Labels: review

#907 Improve ChainHelper testcase
  AElf.Kernel.Types.Tests/ChainHelpersTests.cs
Labels: review

#909 WIP Feature/chain creation service
  AElf.Contracts.Genesis2/BasicContractZero.cs
  AElf.Contracts.Genesis2/BasicContractZeroHelper.cs
  AElf.Contracts.Genesis2/BasicContractZeroState.cs
  AElf.Contracts.Genesis2/Events.cs
  AElf.Kernel.ChainController/Application/ChainCreationService.cs
  AElf.Kernel.ChainController/Application/IChainCreationService.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Core/SmartContract/Application/ISystemContractService.cs
  AElf.Kernel.Core/SmartContract/Domain/SmartContractManager.cs
  AElf.Kernel.Node/Application/IBlockchainNodeContextService.cs
  AElf.Kernel.Node/NodeAElfModule.cs
  AElf.Kernel.SmartContract/Application/IDefaultContractZeroCodeProvider.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.SmartContract/Application/ISmartContractService.cs
  AElf.Kernel.SmartContract/Application/SmartContractService.cs
  AElf.Kernel.SmartContract/Contexts/SmartContractContext.cs
  AElf.Kernel.SmartContract/SmartContractAElfModule.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel.Types/SmartContract/ISmartContractZero.cs
  AElf.Launcher/AElf.Launcher.csproj
  AElf.Launcher/GenesisTransactionsGenerator.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.OS.Core/Node/Application/IOsBlockchainNodeContextService.cs
  AElf.Runtime.CSharp2/SmartContractRunnerForCategoryTwo.cs
  AElf.Sdk.CSharp2/Context.cs
  AElf.Sdk.CSharp2/IContext.cs
  AElf.Sdk.CSharp2/State/FuncInfo.cs
  protobuf/contract_info.proto
  protobuf/kernel.proto
Labels: review

#910 Change ChainOptions.ChainId string --> int, to avoid convert to int (in many class)
  AElf.Kernel.Consensus/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Core/ChainOptions.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Handlers/TxReceivedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.OS.Tests/Network/GrpcPeerPoolTests.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
  AElf.OS.Tests/Network/Sync/Unit/PeerConnectedEventHandlerTests.cs
  AElf.RPC.Tests/TestsRpcAElfModule.cs
Labels: review

#915 Enable single node run with DPoS consensus
  AElf.Common/GlobalConfig.cs
  AElf.Contracts.Consensus.DPoS/Contract_Consensus.cs
  AElf.Contracts.Consensus.DPoS/Contract_Election.cs
  AElf.Contracts.Consensus.DPoS/Contract_Helpers.cs
  AElf.Contracts.Consensus.DPoS/Contract_Process.cs
  AElf.Contracts.Consensus.DPoS/Contract_Process_Helper.cs
  AElf.Contracts.Consensus.DPoS/DPoSContractConsts.cs
  AElf.Contracts.Consensus.DPoS/DPoSContractState.cs
  AElf.Contracts.Consensus.DPoS/DividendContractReferenceState.cs
  AElf.Contracts.Consensus.DPoS/Extensions/ConsensusExtensions.cs
  AElf.Contracts.Consensus.DPoS/Extensions/MinerExtensions.cs
  AElf.Contracts.Consensus.DPoS/Extensions/RoundExtensions.cs
  AElf.Contracts.Consensus.DPoS/Extensions/TermSnapshotExtensions.cs
  AElf.Contracts.Consensus.DPoS/Extensions/VotingRecordExtensions.cs
  AElf.Contracts.Consensus.DPoS/TokenContractReferenceState.cs
  AElf.Contracts.Consensus.Tests/AElf.Contracts.Consensus.Tests.csproj
  AElf.Contracts.Consensus.Tests/ConsensusContractTestAElfModule.cs
  AElf.Contracts.Consensus.Tests/ConsensusContractTestBase.cs
  AElf.Contracts.Consensus.Tests/ConsensusElectionTest.cs
  AElf.Contracts.Consensus.Tests/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/MockSetup.cs
  AElf.Contracts.TestBase/ContractTestAElfModule.cs
  AElf.Contracts.TestBase/ContractTestBase.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSInformationGenerationService.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsensusModule.cs
  AElf.Kernel.Consensus.Scheduler.FluentScheduler/AElf.Kernel.Consensus.Scheduler.FluentScheduler.csproj
  AElf.Kernel.Consensus.Scheduler.FluentScheduler/FluentSchedulerScheduler.cs
  AElf.Kernel.Consensus.Scheduler.RxNet/RxNetObserver.cs
  AElf.Kernel.Consensus.Scheduler.RxNet/RxNetScheduler.cs
  AElf.Kernel.Consensus.Scheduler.RxNet/RxNetSchedulerAElfModule.cs
  AElf.Kernel.Consensus/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Consensus/Application/ConsensusService.cs
  AElf.Kernel.Consensus/Application/IConsensusScheduler.cs
  AElf.Kernel.Consensus/Infrastructure/ConsensusCommand.cs
  AElf.Kernel.Consensus/Infrastructure/ConsensusControlInformation.cs
  AElf.Kernel.Consensus/Infrastructure/IConsensusCommand.cs
  AElf.Kernel.Core/Blockchain/Application/BlockExtraDataService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExtraDataProvider.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExtraDataService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockGenerationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Domain/MinersManager.cs
  AElf.Kernel.Core/EventMessages/BlockMiningEventData.cs
  AElf.Kernel.Core/Extensions/ConsensusExtensions.cs
  AElf.Kernel.Core/Miner/Application/MineBlockEvent.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel/AElf.Kernel.csproj
  AElf.Kernel/KernelAElfModule.cs
  AElf.Kernel/Services/IBlockGenerationService.cs
  AElf.Kernel/Services/IConsensusService.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Launcher/appsettings.json
  AElf.sln
  protobuf/consensus.proto
Labels: review

#895 Refactor/block validation
  AElf.ChainController.Rpc.Tests/AElf.ChainController.Rpc.Tests.csproj
  AElf.Kernel.ChainController/Application/BlockValidationService.cs
  AElf.Kernel.ChainController/Application/Filters/BlockValidationFilter.cs
  AElf.Kernel.ChainController/Application/Filters/IBlockValidationFilter.cs
  AElf.Kernel.ChainController/Application/IBlockValidationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockValidationProvider.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockValidationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Blockchain/Domain/ISecondChainManager.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Tests/AElf.Kernel.Tests.csproj
  AElf.Kernel.Tests/Blockchain/Application/BlockValidationProviderTests.cs
  AElf.Kernel.Tests/Blockchain/Domain/ChainManagerTests.cs
  AElf.Kernel.Tests/Managers/BlockManagerTests.cs
  AElf.Kernel.Tests/Managers/ChainManagerTests.cs
  AElf.Kernel.Tests/Managers/MinersManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionReceiptManagerTests.cs
  AElf.Kernel.Tests/SmartContractExecution/Domain/BlockchainStateManagerTests.cs
  AElf.Kernel.Tests/TransactionTests.cs
  AElf.Runtime.CSharp2.Tests/AElf.Runtime.CSharp2.Tests.csproj
  AElf.Runtime.CSharp2.Tests/TestCSharpRuntimeAElfModule.cs
  protobuf/kernel.proto
Labels: review

#921 Add some unit test
  AElf.Types.Tests/AddressTest.cs
  AElf.Types.Tests/Base58Tests.cs
  AElf.Types.Tests/Extensions/ExtensionTests.cs
  AElf.Types.Tests/HashTests.cs
  AElf.Types.Tests/Helpers/ByteArrayHelpersTests.cs
Labels: review

#919 Implementation of a simple contract testing framework
  AElf.Contracts.Consensus.DPoS/Config.cs
  AElf.Contracts.Consensus.DPoS/Contract_Consensus.cs
  AElf.Contracts.Consensus.DPoS/Contract_Process.cs
  AElf.Contracts.Consensus.Tests/AElf.Contracts.Consensus.Tests.csproj
  AElf.Contracts.Consensus.Tests/ConsensusContractTestAElfModule.cs
  AElf.Contracts.Consensus.Tests/ConsensusElectionTest.cs
  AElf.Contracts.Consensus.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.Tests/ContractTester.cs
  AElf.Contracts.Consensus.Tests/ContractsShim.cs
  AElf.Contracts.Consensus.Tests/MockSetup.cs
  AElf.Contracts.Consensus.Tests/ProcessTest.cs
  AElf.Contracts.TestBase/ContractTestAElfModule.cs
  AElf.Contracts.TestBase/ContractTestBase.cs
  AElf.Kernel.Consensus.DPoS/AElf.Kernel.Consensus.DPoS.csproj
  AElf.Kernel.Consensus.DPoS/DPoSConsensusAElfModule.cs
  AElf.Kernel.Consensus.Scheduler.FluentScheduler/FluentSchedulerAElfModule.cs
  AElf.Kernel.Consensus.Scheduler.FluentScheduler/FluentSchedulerScheduler.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel/AElf.Kernel.csproj
  AElf.Kernel/KernelAElfModule.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Runtime.CSharp.Core/AssebmlyChecker.cs
  AElf.TestBase/AElfIntegratedTest.cs
Labels: review

#904 Refactor unit test cases
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Cryptography.Tests/Certificate/CertGeneratorTest.cs
  AElf.Cryptography.Tests/Certificate/CertificateStoreTests.cs
  AElf.Cryptography.Tests/Certificate/PemWriterTest.cs
  AElf.Cryptography.Tests/ECDSA/TransactionSignatureTest.cs
  AElf.Database.Tests/HelperTests.cs
  AElf.Database.Tests/KeyValueDbContextTestBase.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.Tests/Managers/BlockManagerTests.cs
  AElf.Kernel.Tests/Managers/MinersManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionManagerTests.cs
  AElf.Kernel.Tests/Managers/TransactionReceiptManagerTests.cs
  AElf.Kernel.TransactionPool.Tests/AElf.Kernel.TransactionPool.Tests.csproj
  AElf.Kernel.TransactionPool.Tests/FakeTransaction.cs
  AElf.Kernel.TransactionPool.Tests/TransactionPoolAElfModule.cs
  AElf.Kernel.TransactionPool.Tests/TransactionPoolTestBase.cs
  AElf.Kernel.TransactionPool.Tests/TxHubTests.cs
  AElf.Kernel.TransactionPool.Tests/TxRefBlockValidatorTests.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.OS.Tests/Network/GrpcNetworkServerTests.cs
  AElf.Sdk.CSharp.Tests/AElf.Sdk.CSharp.Tests.csproj
  AElf.Sdk.CSharp.Tests/ContractTest.cs
  AElf.Sdk.CSharp.Tests/MockChainService.cs
  AElf.Sdk.CSharp.Tests/MockStateManager.cs
  AElf.Sdk.CSharp.Tests/MockStateProvider.cs
  AElf.Sdk.CSharp.Tests/MockStateProviderFactory.cs
  AElf.Sdk.CSharp.Tests/SafeMathTests.cs
  AElf.Sdk.CSharp.Tests/SdkCSharpTestBase.cs
  AElf.Sdk.CSharp.Tests/StateTest.cs
  AElf.Sdk.CSharp.Tests/TestSdkCSharpAElfModule.cs
  AElf.Sdk.CSharp2.Tests/SafeMathTests.cs
  AElf.Sdk.CSharp2.Tests/SdkCSharpTestBase.cs
  AElf.Sdk.CSharp2.Tests/TestSdkCSharpAElfModule.cs
  AElf.Types.Tests/AddressTest.cs
  AElf.Types.Tests/Base58Tests.cs
  AElf.Types.Tests/Extensions/ExtensionTests.cs
  AElf.Types.Tests/HashTests.cs
  AElf.Types.Tests/Helpers/ByteArrayHelpersTests.cs
Labels: review

#885 New interface for IBlockExecutingService and calculate merkle trees
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
Labels: review

#908 [WIP] Fix request block test case
  AElf.OS.Core/AElf.OS.Core.csproj
  AElf.OS.Core/CoreOSAElfModule.cs
  AElf.OS.Core/Network/Generated/.gitkeep
  AElf.OS.Core/Network/IAElfNetworkServer.cs
  AElf.OS.Core/Network/IAElfServerService.cs
  AElf.OS.Core/Network/IPeer.cs
  AElf.OS.Core/Network/IPeerPool.cs
  AElf.OS.Core/Network/NetworkConsts.cs
  AElf.OS.Core/Network/Temp/IBlockService.cs
  AElf.OS.Network.Grpc/GrpcNetworkService.cs
  AElf.OS.Network.Grpc/GrpcPeer.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Network.Grpc/GrpcUrl.cs
  AElf.OS.Network.Grpc/IPeerPool.cs
  AElf.OS.Tests/Network/GrpcNetworkManagerTests.cs
  AElf.sln
  protobuf/network_types.proto
  protobuf/peer_service.proto
Labels: review

#934 block execution
  AElf.Kernel.Core/Blockchain/Application/IBlockValidationProvider.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockValidationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Blockchain/Domain/IChainManager.cs
  AElf.Kernel.Tests/Blockchain/Domain/ChainManagerTests.cs
  protobuf/kernel.proto
Labels: review

#936 blockchain executing service
  AElf.Contracts.Consensus.Tests/ContractTester.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
Labels: review

#933 Improve aelf.js dependence
  .gitignore
  .travis.yml
  AElf.CLI/AElf.CLI.csproj
  AElf.CLI/JS/JSEngine.cs
  AElf.CLI/Scripts/aelf.js
  AElf.CLI/package.json
Labels: review

#932 Cleanup common project
  AElf.CLI/yarn.lock
  AElf.Common/Application/ApplicationHelpers.cs
  AElf.Common/Extensions/ExpressionExtensions.cs
  AElf.Kernel.ChainController/Application/ChainCreationService.cs
  AElf.Kernel.Core/Blockchain/Domain/IChainManager.cs
  AElf.Kernel.Core/Blockchain/Helpers/GenesisBlockBuilder.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/BlockBodyStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/BlockHeaderStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/TransactionStore.cs
  AElf.Kernel.Core/Infrastructure/BinaryMerkleTreeStore.cs
  AElf.Kernel.Core/Infrastructure/MinersStore.cs
  AElf.Kernel.Core/SmartContract/Domain/SmartContractStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/CallGraphStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/FunctionMetadataStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/StateStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/TransactionResultStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/TransactionTraceStore.cs
  AElf.Kernel.Core/TransactionPool/Infrastructure/TransactionReceiptStore.cs
  AElf.Kernel.SmartContractExecution/MockResourceUsageDetectionService.cs
  AElf.Kernel.SmartContractExecution/Protobuf/ProtobufSerializer.cs
  AElf.Kernel.Tests/Blockchain/Domain/ChainManagerTests.cs
  AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  AElf.Kernel.TransactionPool/TxRefBlockValidator.cs
  AElf.Kernel.Types/Consts.cs
  AElf.Kernel.Types/KernelTypesConsts.cs
  AElf.Launcher/Properties/launchSettings.json
  AElf.OS.Core/CoreOSAElfModule.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Rpc.Wallet/WalletRpcService.cs
  AElf.Runtime.CSharp/Executive.cs
  AElf.Runtime.CSharp/SmartContractRunnerForCategoryTwo.cs
Labels: review

#920 Added a few handlers
  AElf.Kernel.Consensus.DPoS/DPoSConsensusAElfModule.cs
  AElf.Kernel.Consensus/Application/BestChainFoundEventHandler.cs
  AElf.Kernel.Core/Blockchain/Domain/IBlockManager.cs
  AElf.Kernel.Core/Blockchain/Events/BlockAcceptedEvent.cs
  AElf.Kernel.SmartContract/Contexts/StateProvider.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel/KernelAElfModule.cs
  AElf.Kernel/Services/BlockMiningEventHandler.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.OS.Core/AElf.OS.Core.csproj
  AElf.OS.Core/CoreOSAElfModule.cs
  AElf.OS.Core/Handlers/BlockAcceptedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Core/Jobs/ForkDownloadJobArgs.cs
  AElf.OS.Core/Node/Application/IAElfNetworkServer.cs
  AElf.OS.Core/Node/Application/IOsBlockchainNodeContextService.cs
  AElf.OS.Core/Node/Domain/OsBlockchainNodeContext.cs
  AElf.OS.Network.Grpc/GrpcNetworkModule.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
Labels: review

#942 refactor storage
  AElf.Kernel.Core/Blockchain/Domain/IBlockManager.cs
  AElf.Kernel.Core/Blockchain/Domain/TransactionManager.cs
  AElf.Kernel.Core/Blockchain/Domain/TransactionResultManager.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/BlockBodyStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/BlockHeaderStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/IBlockBodyStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/IBlockHeaderStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/IBlockchainStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/ITransactionStore.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/TransactionStore.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Core/Domain/BinaryMerkleTreeManager.cs
  AElf.Kernel.Core/Domain/MinersManager.cs
  AElf.Kernel.Core/Infrastructure/BinaryMerkleTreeStore.cs
  AElf.Kernel.Core/Infrastructure/IBinaryMerkleTreeStore.cs
  AElf.Kernel.Core/Infrastructure/IKeyValueStore.cs
  AElf.Kernel.Core/Infrastructure/IMinersStore.cs
  AElf.Kernel.Core/Infrastructure/KeyValueStoreBase.cs
  AElf.Kernel.Core/Infrastructure/MinersStore.cs
  AElf.Kernel.Core/SmartContract/Domain/FunctionMetadataManager.cs
  AElf.Kernel.Core/SmartContract/Domain/ISmartContractStore.cs
  AElf.Kernel.Core/SmartContract/Domain/SmartContractManager.cs
  AElf.Kernel.Core/SmartContract/Domain/SmartContractStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/CallGraphStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/FunctionMetadataStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/ICallGraphStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/IFunctionMetadataStore.cs
  AElf.Kernel.Core/SmartContractExecution/Domain/TransactionTraceManager.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/IStateStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/ITransactionResultStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/ITransactionTraceStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/StateStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/TransactionResultStore.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/TransactionTraceStore.cs
  AElf.Kernel.Core/TransactionPool/Domain/TransactionReceiptManager.cs
  AElf.Kernel.Core/TransactionPool/Infrastructure/ITransactionReceiptStore.cs
  AElf.Kernel.Core/TransactionPool/Infrastructure/TransactionReceiptStore.cs
  AElf.Kernel.Types/KernelTypesConsts.cs
Labels: review

#938 Refactor contract test cases
  AElf.Contracts.TestBase/AElf.Contracts.TestBase.csproj
  AElf.Contracts.TestBase/ContractTestAElfModule.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Contracts.Token.Tests/AElf.Contracts.Token.Tests.csproj
  AElf.Contracts.Token.Tests/ContractZeroShim.cs
  AElf.Contracts.Token.Tests/MockSetup.cs
  AElf.Contracts.Token.Tests/TokenContractShim.cs
  AElf.Contracts.Token.Tests/TokenContractTest.cs
  AElf.Contracts.Token.Tests/TokenContractTestAElfModule.cs
  AElf.Contracts.Token.Tests/TokenContractTestBase.cs
Labels: review

#946 remove serailizers
  AElf.Common/Serializers/IByteSerializer.cs
  AElf.Common/Serializers/ProtobufSerializer.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/IBlockchainStore.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Core/Infrastructure/KeyValueStoreBase.cs
  AElf.Kernel.Core/SmartContractExecution/Infrastructure/StateStore.cs
  scripts/build.sh
Labels: review

#931 Network improvements
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.OS.Core/CoreOSAElfModule.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.OS.Core/Network/NetworkOptions.cs
  AElf.OS.Network.Grpc/GrpcPeer.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Tests/Network/Sync/SyncTester.cs
  AElf.OS.Tests/Network/Sync/Unit/PeerConnectedEventHandlerTests.cs
Labels: review

#950 Delete unused projects, rename class files
  AElf.Contracts.TestBase.Tests/AElf.Contracts.TestBase.Tests.csproj
  AElf.Contracts.TestBase/ContractTestAElfModule.cs
  AElf.Launcher/LauncherAElfModule.cs
  AElf.Runtime.CSharp.Tests/TestCSharpRuntimeAElfModule.cs
  AElf.Runtime.CSharp/CSharpRuntimeAElfModule.cs
  AElf.Sdk.CSharp2.Tests/SafeMathTests.cs
  AElf.Sdk.CSharp2.Tests/SdkCSharpTestBase.cs
  AElf.Sdk.CSharp2.Tests/TestSdkCSharpAElfModule.cs
Labels: review

#949 Add docker scripts
  docker/docker-compose.yml
  docker/start-cli.sh
  docker/start-node.sh
Labels: review

#953 Fixed initial sync.
  AElf.Contracts.TestBase.Tests/AElf.Contracts.TestBase.Tests.csproj
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.RuntimeSetup/log4net.config
Labels: review

#951 Update TokenContract Test
  AElf.Contracts.Token.Tests/TokenContractTest.cs
Labels: review

#943 Write resource contract test cases
  AElf.Contract.Resource.Tests/ResourceContractTest.cs
  AElf.Contracts.TestBase.Tests/AElf.Contracts.TestBase.Tests.csproj
  AElf.Contracts.TestBase/AElf.Contracts.TestBase.csproj
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Contracts.Token.Tests/TokenContractTest.cs
Labels: review

#954 Implement consensus validation and fix some bugs on consensus contract.
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ContractTesterConsensusExtensions.cs
  AElf.Contracts.Consensus.DPoS/Contract_Helpers.cs
  AElf.Contracts.Consensus.DPoS/Contract_Kernel.cs
  AElf.Contracts.Consensus.DPoS/DPoSContractConsts.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSConsensusValidationProvider.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSInformationGenerationService.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsensusAElfModule.cs
  AElf.Kernel.Consensus.DPoS/DPoSOptions.cs
  AElf.Kernel.Consensus.Scheduler.RxNet/RxNetScheduler.cs
  AElf.Kernel.Consensus/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Consensus/Application/ConsensusService.cs
  AElf.Kernel.Consensus/Application/IConsensusInformationGenerationService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Domain/IChainManager.cs
  AElf.Kernel.Tests/Blockchain/Domain/ChainManagerTests.cs
  AElf.Launcher/Properties/launchSettings.json
  AElf.Launcher/appsettings.json
  AElf.Sdk.CSharp/IConsensusSmartContract.cs
  protobuf/consensus.proto
Labels: review

#955 add LogDebug to SDK, it will only work in DEBUG mode
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.SmartContract/Contexts/ISmartContractContext.cs
  AElf.Kernel.SmartContract/Contexts/SmartContractContext.cs
  AElf.Sdk.CSharp.Tests/ContractTest.cs
  AElf.Sdk.CSharp/Context.cs
  AElf.Sdk.CSharp/FeeAttribute.cs
  AElf.Sdk.CSharp/IContext.cs
  AElf.Sdk.CSharp/ProtobufSerializer.cs
Labels: review

#957 do not need config database
  AElf.Contracts.Consensus.DPoS/Contract_Election.cs
  AElf.Contracts.TestBase/ContractTester.cs
Labels: review

#945 improve unit test - 0226
  AElf.Kernel.SmartContract.Tests/AElf.Kernel.SmartContract.Tests.csproj
  AElf.Kernel.SmartContract.Tests/Application/SmartContractExecutiveServiceTests.cs
  AElf.Kernel.SmartContract.Tests/Application/SmartContractServiceTests.cs
  AElf.Kernel.SmartContract.Tests/Infrastructure/SmartContractRunnerContainerTests.cs
  AElf.Kernel.SmartContract.Tests/SmartContractTestAElfModule.cs
  AElf.Kernel.SmartContract.Tests/SmartContractTestBase.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.SmartContractExecution.Tests/AElf.Kernel.SmartContractExecution.Tests.csproj
  AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutingServiceTests.cs
  AElf.Kernel.SmartContractExecution.Tests/Scheduling/GrouperTests.cs
  AElf.Kernel.SmartContractExecution.Tests/Scheduling/UnionFindNodeTest.cs
  AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionTestAElfModule.cs
  AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionTestBase.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.Tests/SmartContract/Domain/FunctionMetadataManagerTests.cs
  AElf.Kernel.Tests/SmartContract/Domain/SmartContractManagerTests.cs
  AElf.sln
Labels: review

#980 change address format
  AElf.CLI/AElf.CLI.csproj
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Types.Tests/AddressTest.cs
  AElf.Types/Address.cs
Labels: review

#973 Refactor unit cases
  AElf.Contract.Resource.Tests/ResourceContractTest.cs
  AElf.Contracts.TestBase/AElf.Contracts.TestBase.csproj
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Kernel.Core/Extensions/TransactionTraceExtensions.cs
  AElf.Runtime.CSharp.Tests/AElf.Runtime.CSharp.Tests.csproj
  AElf.Runtime.CSharp.Tests/CSharpRuntimeTestBase.cs
  AElf.Runtime.CSharp.Tests/SmartContractRunnerTest.cs
  AElf.Runtime.CSharp.Tests/TestCSharpRuntimeAElfModule.cs
  AElf.Sdk.CSharp.Tests/SafeMathTests.cs
  AElf.Sdk.CSharp/CSharpSmartContract`.cs
Labels: review

#989 trigger contract events
  AElf.CrossChain.Core/Services/CrossChainService.cs
  AElf.Kernel.Consensus/Application/BestChainFoundEventHandler.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockExecutingService.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Blockchain/Events/BestChainFoundEventData.cs
  AElf.Kernel.Tests/Blockchain/Application/FullBlockchainExecutingServiceTests.cs
  AElf.Kernel.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  AElf.Kernel/LibBestChainFoundEventHandler.cs
Labels: review

#994 split attach block to chain and block executing
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Kernel.ChainController.Tests/ChainControllerTestAElfModule.cs
  AElf.Kernel.ChainController/AElf.Kernel.ChainController.csproj
  AElf.Kernel.ChainController/Application/ChainCreationService.cs
  AElf.Kernel.ChainController/ChainControllerAElfModule.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.SmartContractExecution.Akka/Infrastructure/ActorEnvironment.cs
  AElf.Kernel.SmartContractExecution.Tests/Application/FullBlockchainExecutingServiceTests.cs
  AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionTestAElfModule.cs
  AElf.Kernel.SmartContractExecution/AElf.Kernel.SmartContractExecution.csproj
  AElf.Kernel.SmartContractExecution/Application/IBlockExecutingService.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel.SmartContractExecution/SmartContractExecutionAElfModule.cs
  AElf.Kernel.TestBase/AElf.Kernel.TestBase.csproj
  AElf.Kernel.TestBase/Class1.cs
  AElf.Kernel.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  AElf.Kernel.Tests/KernelTestAElfModule.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.OS.Core/Handlers/PeerConnectedEventHandler.cs
  AElf.OS.Core/Jobs/ForkDownloadJob.cs
  AElf.sln
Labels: review

#996 add a test base to initialize database config and other common configs
  AElf.Kernel.TestBase/AElf.Kernel.TestBase.csproj
  AElf.Kernel.TestBase/Class1.cs
  AElf.Kernel.TestBase/KernelTestAElfModule.cs
  AElf.Kernel.Tests/AElf.Kernel.Tests.csproj
  AElf.Kernel.Tests/KernelTestAElfModule.cs
Labels: review

#999 Update contract unit test
  AElf.Contracts.Genesis.Tests/AElf.Contracts.Genesis.Tests.csproj
  AElf.Contracts.Genesis.Tests/ContractZeroTest.cs
  AElf.Contracts.Genesis.Tests/GenesisContractTest.cs
  AElf.Contracts.Genesis.Tests/GenesisContractTestAElfModule.cs
  AElf.Contracts.Genesis.Tests/GenesisContractTestBase.cs
  AElf.Contracts.Genesis.Tests/MockSetup.cs
  AElf.Contracts.Genesis.Tests/TestContractShim.cs
  AElf.Contracts.Token.Tests/TokenContractTest.cs
Labels: review

#970 Refactor txhub
  AElf.CLI/Scripts/contract.js
  AElf.CLI/Scripts/init-chain.js
  AElf.CLI/Scripts/requestor.js
  AElf.CLI/package.json
  AElf.CLI/yarn.lock
  AElf.Contracts.TestBase.Tests/ContractTesterTest.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.CrossChain.Core/Helpers/ICrossChainReadOnlyTransactionExecutor.cs
  AElf.Crosschain.Tests/CrosschainTestHelper.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/Blockchain/Domain/IBlockManager.cs
  AElf.Kernel.Core/Blockchain/Events/NewIrreversibleBlockFoundEvent.cs
  AElf.Kernel.Core/Extensions/TransactionExtensions.cs
  AElf.Kernel.Core/Extensions/TransactionResultExtensions.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel.TransactionPool.Tests/TxHubTests.cs
  AElf.Kernel.TransactionPool/AElf.Kernel.TransactionPool.csproj
  AElf.Kernel.TransactionPool/Application/TxPoolInterestedEventsHandler.cs
  AElf.Kernel.TransactionPool/Infrastructure/ITxHub.cs
  AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  AElf.OS.Rpc.ChainController/ITransactionResultService.cs
  AElf.OS.Rpc.ChainController/ServiceExtensions.cs
  AElf.OS.Rpc.ChainController/TransactionResultService.cs
  AElf.OS.Rpc.Core/AElf.OS.Rpc.Core.csproj
  AElf.OS.Rpc.Core/RpcAElfModule.cs
  AElf.Sdk.CSharp/State/FuncInfo.cs
  protobuf/kernel.proto
Labels: review

#971 Fixed bugs about DPoS consensus and implemented LIB found logic.
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.DPoS/Contract_Helpers.cs
  AElf.Contracts.Consensus.DPoS/Contract_Kernel.cs
  AElf.Contracts.Consensus.DPoS/Contract_Process.cs
  AElf.Contracts.Consensus.DPoS/Events.cs
  AElf.Contracts.Consensus.DPoS/Extensions/MinerExtensions.cs
  AElf.Kernel.Consensus.DPoS.Tests/AElf.Kernel.Consensus.DPoS.Tests.csproj
  AElf.Kernel.Consensus.DPoS.Tests/ConsensusCommonTest.cs
  AElf.Kernel.Consensus.DPoS.Tests/ConsensusServiceTest.cs
  AElf.Kernel.Consensus.DPoS.Tests/ConsensusTestHelper.cs
  AElf.Kernel.Consensus.DPoS.Tests/ConsensusTestHelperTest.cs
  AElf.Kernel.Consensus.DPoS.Tests/ConsensusTester.cs
  AElf.Kernel.Consensus.DPoS.Tests/DPoSConsensusTestAElfModule.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSInformationGenerationService.cs
  AElf.Kernel.Consensus.Scheduler.RxNet/RxNetScheduler.cs
  AElf.Kernel.Consensus/Application/ConsensusService.cs
  AElf.Kernel.SmartContractExecution/Application/IBlockExecutingService.cs
  AElf.Kernel.SmartContractExecution/Application/ITransactionExecutingService.cs
  AElf.Kernel/LibBestChainFoundEventHandler.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.Launcher/LauncherAElfModule.cs
  protobuf/consensus.proto
Labels: review

#998 Continue add basic unit cases
  AElf.Contract.Resource.Tests/BancorHelpTests.cs
  AElf.Contract.Resource.Tests/ResourceContractTest.cs
  AElf.Contracts.Token/TokenContract_Actions.cs
  AElf.Runtime.CSharp.Tests/AElf.Runtime.CSharp.Tests.csproj
  AElf.Types.CSharp.Tests/ConversionExtensionTests.cs
  AElf.Types.CSharp/ConversionExtension.cs
Labels: review

#1001 Improve unit test - sdk context
  AElf.Sdk.CSharp.Tests/AElf.Sdk.CSharp.Tests.csproj
  AElf.Sdk.CSharp.Tests/ContextTests.cs
  AElf.Sdk.CSharp.Tests/TestSdkCSharpAElfModule.cs
  AElf.Sdk.CSharp/Context.cs
Labels: review

#1004 Add unit test
  AElf.Contracts.Token.Tests/TokenContractTest.cs
  AElf.Types.Tests/AElf.Types.Tests.csproj
  AElf.Types.Tests/AddressTest.cs
  AElf.Types/Address.cs
Labels: review

#1005 improve event performance
  AElf.Contracts.Consensus.DPoS/Events.cs
  AElf.Contracts.CrossChain/Events.cs
  AElf.Contracts.Genesis/Events.cs
  AElf.Contracts.Resource/Events.cs
  AElf.Contracts.Token/Events.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.Sdk.CSharp.Tests.TestContract/Events.cs
  AElf.Sdk.CSharp/Event.cs
  protobuf/kernel.proto
Labels: review

#1006 change coverlet
  AElf.Database/KeyValueDbContext.cs
  AElf.Kernel.SmartContract.Tests/AElf.Kernel.SmartContract.Tests.csproj
  scripts/test.sh
Labels: review

#1007 test
  scripts/test.sh
Labels: review

#1008 move blockchain state manager
  AElf.Contract.Resource.Tests/ResourceContractTest.cs
  AElf.Contracts.Consensus.DPoS/Events.cs
  AElf.Contracts.CrossChain/Events.cs
  AElf.Contracts.Genesis/Events.cs
  AElf.Contracts.Resource/Events.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Contracts.Token/Events.cs
  AElf.Kernel.Core/Blockchain/Domain/TransactionResultManager.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Core/SmartContract/Domain/IBlockchainStateManager.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/IStateStore.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/StateStore.cs
  AElf.Kernel.Core/SmartContractExecution/Domain/TransactionTraceManager.cs
  AElf.Kernel.SmartContract/Contexts/StateProvider.cs
  AElf.Kernel.SmartContract/Contexts/StateProviderFactory.cs
  AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutingServiceTests.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.Tests/SmartContractExecution/Domain/BlockchainStateManagerTests.cs
  AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  AElf.Sdk.CSharp.Tests.TestContract/Events.cs
  AElf.Sdk.CSharp/Context.cs
  AElf.Sdk.CSharp/Event.cs
  AElf.Sdk.CSharp/IContext.cs
Labels: review
