Repository AElfProject/AElf, pull requests merged in 2019-10, with the labels that each got.

#2057 Enable unchecked math validator
  contract/AElf.Contracts.AssociationAuth/AElf.Contracts.AssociationAuth.csproj
  contract/AElf.Contracts.Configuration/AElf.Contracts.Configuration.csproj
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_ViewMethods.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AElf.Contracts.Consensus.AEDPoS.csproj
  contract/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  contract/AElf.Contracts.Economic/AElf.Contracts.Economic.csproj
  contract/AElf.Contracts.Election/AElf.Contracts.Election.csproj
  contract/AElf.Contracts.Genesis/AElf.Contracts.Genesis.csproj
  contract/AElf.Contracts.MultiToken/AElf.Contracts.MultiToken.csproj
  contract/AElf.Contracts.ParliamentAuth/AElf.Contracts.ParliamentAuth.csproj
  contract/AElf.Contracts.Profit/AElf.Contracts.Profit.csproj
  contract/AElf.Contracts.ReferendumAuth/AElf.Contracts.ReferendumAuth.csproj
  contract/AElf.Contracts.TokenConverter/AElf.Contracts.TokenConverter.csproj
  contract/AElf.Contracts.Treasury/AElf.Contracts.Treasury.csproj
  contract/AElf.Contracts.Vote/AElf.Contracts.Vote.csproj
  src/AElf.Runtime.CSharp.Core/Policies/DefaultPolicy.cs
  test/AElf.Runtime.CSharp.Tests.TestContract/AElf.Runtime.CSharp.Tests.TestContract.csproj
Labels: review

#2095 add view information and api in election contract
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContractConstants.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_ViewMethods.cs
  contract/AElf.Contracts.Election/ElectionContract_Elector.cs
  contract/AElf.Contracts.Election/ViewMethods.cs
  contract/AElf.Contracts.Vote/VoteContract.cs
  protobuf/aedpos_contract.proto
  protobuf/election_contract.proto
  protobuf/vote_contract.proto
  test/AElf.Contracts.Consensus.AEDPoS.Tests/BVT/ViewTests.cs
  test/AElf.Contracts.Election.Tests/BVT/ElectionViewTests.cs
Labels: backlog

#2137 Improve gCP tutorial.
  docs/tutorials/GCP.md
  docs/tutorials/depl.png
  docs/tutorials/deployed.png
  docs/tutorials/gcp-step1.png
  docs/tutorials/gcp-step2-a.png
  docs/tutorials/gcp-step2-b.png
  docs/tutorials/ssh-select.png
  docs/tutorials/ssh.png
Labels: docs
