Repository AElfProject/AElf, pull requests merged in 2019-04, with the labels that each got.

#1473 Add web api unit test
  AElf.WebApp.Application.Chain.Tests/AElf.WebApp.Application.Chain.Tests.csproj
  AElf.WebApp.Application.Chain.Tests/ChainAppServiceTest.cs
  AElf.WebApp.Application.Chain/ChainAppService.cs
  AElf.WebApp.Application.Chain/Dto/BlockInfoDto.cs
  AElf.WebApp.Application.Chain/Error.cs
  AElf.WebApp.Application.TestBase/AElf.WebApp.Application.TestBase.csproj
  AElf.WebApp.Application.TestBase/WebAppErrorResponse.cs
  AElf.WebApp.Application.TestBase/WebAppTestAElfModule.cs
  AElf.WebApp.Application.TestBase/WebAppTestBase.cs
  AElf.WebApp.Application.TestBase/WebAppTestStartup.cs
  AElf.sln
Labels: review

#1476 Change version 0.7.0.17987 --> 0.7.0-alpha.1-17987
  scripts/deploy_myget_daily.sh
Labels: review

#1478 remove files
  AElf.TxPool/TransactionFilter.cs
  AElf.TxPool/TxHub.cs
Labels: review

#1481 make logging can be logged into xunit output
  AElf.Database.Benches/DatabaseTests.cs
  AElf.OS.Rpc.TestBase/AElf.OS.Rpc.TestBase.csproj
  AElf.TestBase/AElf.TestBase.csproj
  AElf.TestBase/AElfIntegratedTest.cs
  AElf.TestBase/TestBaseAElfModule.cs
  AElf.WebApp.Application.TestBase/AElf.WebApp.Application.TestBase.csproj
Labels: review

#1471 Improve uncovered test cases
  AElf.Contracts.Dividend.Tests/DividendContractTests.cs
  AElf.Contracts.Resource.FeeReceiver.Tests/FeeReceiverContractTests.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.CrossChain.Grpc.Tests/GrpcClientTests.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainClientNodePluginTest.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainClientTestModule.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainServerNodePluginTest.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainServerTestBase.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainServerTestModule.cs
  AElf.CrossChain.Grpc.Tests/GrpcServerTests.cs
  AElf.Kernel.Core.Tests/Blockchain/Domain/BlockChainHelperTests.cs
  AElf.Kernel.Tests/BlockMiningEventHandlerTests.cs
  AElf.Kernel.Tests/KernelTestAElfModule.cs
  AElf.Kernel.Tests/MinerServiceTests.cs
  AElf.Kernel.Types.Tests/Block/BlockTests.cs
  AElf.Kernel.Types/Block/BlockBody.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs
  AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  AElf.OS.Rpc.TestBase/RpcTestBase.cs
  AElf.Sdk.CSharp.Tests/MockStates.cs
  AElf.Sdk.CSharp.Tests/StateTest.cs
  AElf.Types.CSharp.Tests/AElf.Types.CSharp.Tests.csproj
  AElf.Types.CSharp.Tests/PreconditionsTests.cs
  AElf.Types.CSharp.Tests/TypesCSharpTestAElfModule.cs
  AElf.Types.CSharp.Tests/TypesCSharpTestBase.cs
  AElf.Types.CSharp/Utils/Preconditions.cs
Labels: review

#1482 Feature reorg mining and types
  AElf.Contracts.TestKit/AElf.Contracts.TestKit.csproj
  AElf.Contracts.TestKit/TransactionExecutor.cs
  AElf.Cryptography/CryptoHelpers.cs
  AElf.Kernel.Core.Tests/SmartContract/Application/BlockchainStateMergingServiceTests.cs
  AElf.Kernel.Core/Blockchain/Infrastructure/IBlockchainStore.cs
  AElf.Kernel.Core/CoreKernelAElfModule.cs
  AElf.Kernel.Core/Infrastructure/KeyValueStoreBase.cs
  AElf.Kernel.Core/Miner/Application/IMinerService.cs
  AElf.Kernel.Core/SmartContract/Application/IBlockchainStateMergingService.cs
  AElf.Kernel.Core/SmartContract/Domain/IBlockchainStateManager.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/StateStore.cs
  AElf.Kernel/Services/MinerService.cs
  AElf.Sdk.CSharp/IConsensusSmartContract.cs
  AElf.Types.CSharp/ConversionExtension.cs
  AElf.Types.Tests/Helpers/ByteArrayHelpersTests.cs
  AElf.Types/Helpers/ByteArrayHelpers.cs
Labels: review

#1480 Enhancement/block sync
  AElf.Kernel.SmartContractExecution/Application/IBlockAttachService.cs
  AElf.Kernel/Services/BlockMiningEventHandler.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS/Jobs/BlockSyncJob.cs
Labels: review

#1479 Performance - execution
  AElf.Kernel.Core/SmartContract/Infrastructure/StateStore.cs
  AElf.Kernel.SmartContractExecution.Benches/AElf.Kernel.SmartContractExecution.Benches.csproj
  AElf.Kernel.SmartContractExecution.Benches/BlockAttachTests.cs
  AElf.Kernel.SmartContractExecution.Benches/BlockExecutingTests.cs
  AElf.Kernel.SmartContractExecution.Benches/ExecutionBenchAElfModule.cs
  AElf.Kernel.SmartContractExecution.Benches/FullBlockchainExecutingTests.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.OS.TestBase/OSTestHelper.cs
  AElf.sln
Labels: review

#1477 Add test cases to cover net web api: AddPeer, GetPeers, RemovePeers
  AElf.WebApp.Application.Chain.Tests/ChainAppServiceTest.cs
  AElf.WebApp.Application.Net.Tests/AElf.WebApp.Application.Net.Tests.csproj
  AElf.WebApp.Application.Net.Tests/NetAppServiceTest.cs
  AElf.WebApp.Application.TestBase/WebAppErrorResponse.cs
  AElf.WebApp.Application.TestBase/WebAppTestAElfModule.cs
  AElf.WebApp.Application.TestBase/WebAppTestBase.cs
  AElf.sln
Labels: review

#1485 Continue improve unit cases
  AElf.Contracts.CrossChain.Tests/CrossChainIndexingActionTest.cs
  AElf.Core.Tests/TaskQueueTests.cs
  AElf.Kernel.Core.Tests/TransactionPool/Domain/TransactionReceiptManagerTests.cs
  AElf.Kernel.SmartContractExecution.Tests/MockResourceUsageDetectionServiceTests.cs
  AElf.Kernel.SmartContractExecution.Tests/ResourceUsageDetectionServiceTests.cs
  AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionTestAElfModule.cs
  AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionTestBase.cs
  AElf.Kernel.SmartContractExecution/ResourceUsageDetectionService.cs
  AElf.Kernel.Types.Tests/Block/BlockTests.cs
  AElf.Kernel.Types.Tests/Transaction/TransactionParallelMetaDataTests.cs
  AElf.Kernel.Types.Tests/Transaction/TransactionTests.cs
  AElf.Kernel.Types/Helpers/AddressHelpers.cs
  AElf.Runtime.CSharp.Tests/ServerCallHandlerTests.cs
  AElf.Runtime.CSharp/ServerCallHandler.cs
  AElf.Runtime.CSharp/ServerCalls.cs
  AElf.Sdk.CSharp.Tests/TestContractTests.cs
  AElf.Types.CSharp.Tests/AElf.Types.CSharp.Tests.csproj
  AElf.Types.CSharp.Tests/MarshallerTests.cs
  AElf.Types.CSharp.Tests/MetadataAttributeTests.cs
  AElf.Types.CSharp.Tests/MethodTests.cs
Labels: review

#1490 Improve token converter contract
  AElf.Contracts.TokenConverter.Tests/BancorHelpersTest.cs
  AElf.Contracts.TokenConverter.Tests/TokenConverterContractTests.cs
  AElf.Contracts.TokenConverter/TokenConverterContract.cs
  AElf.Contracts.TokenConverter/TokenConverterContractState.cs
  protobuf/token_converter_contract.proto
Labels: review

#1492 Fix a bug about changing term.
  AElf.Consensus.DPoS.Types/BasicExtensions.cs
  AElf.Consensus.DPoS.Types/MiningTimeExtensions.cs
  AElf.Contracts.Consensus.DPoS.SideChain/ConsensusContract/GetConsensusCommand.cs
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/GetConsensusCommand.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Helpers.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/UpdateConsensus.cs
Labels: review

#1493 Use raw tx parameters
  AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  AElf.WebApp.Application.Chain/ChainAppService.cs
Labels: review

#1494 Fix bugs about changing term.
  AElf.Contracts.Consensus.DPoS/ConsensusContract/NextTerm.cs
Labels: review

#1495 Add version to web api and change web api route
  AElf.WebApp.Application.Chain.Tests/ChainAppServiceTest.cs
  AElf.WebApp.Application.Chain.Tests/VersionTestAppServiceTest.cs
  AElf.WebApp.Application.Chain/InfoAppService.cs
  AElf.WebApp.Application.Chain/TestAppService.cs
  AElf.WebApp.Application.Chain/VersionTestAppService.cs
  AElf.WebApp.Application.Net.Tests/NetAppServiceTest.cs
  AElf.WebApp.Application.Net/TestAppService.cs
  AElf.WebApp.Application.TestBase/WebAppTestBase.cs
  AElf.WebApp.Web/AElf.WebApp.Web.csproj
  AElf.WebApp.Web/ConfigureSwaggerOptions.cs
  AElf.WebApp.Web/WebAppAbpServiceConvention.cs
  AElf.WebApp.Web/WebWebAppAElfModule.cs
Labels: review

#1500 Fix sidechain initialization.
  AElf.Blockchains.SideChain/SideChainAElfModule.cs
Labels: review

#1501 Storage key ToHex => ToBase64
  AElf.Kernel.Core.Tests/Blockchain/Domain/ChainManagerTests.cs
  AElf.Kernel.Core/Blockchain/Domain/IBlockManager.cs
  AElf.Kernel.Core/Blockchain/Domain/IChainManager.cs
  AElf.Kernel.Core/Infrastructure/StorageKeyExtensions.cs
  AElf.Kernel.Core/KernelConsts.cs
  AElf.Kernel.Core/SmartContract/Domain/FunctionMetadataManager.cs
  AElf.Kernel.Core/SmartContract/Domain/IBlockchainStateManager.cs
  AElf.Kernel.Core/TransactionPool/Domain/TransactionReceiptManager.cs
  AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  AElf.Types/Hash.cs
  AElf.WebApp.Application.Chain/ChainAppService.cs
Labels: review

#1491 Continue improve unit cases
  AElf.Contracts.Consensus.DPoS.SideChain.Tests/ConsensusContractBasicTests.cs
  AElf.Contracts.Consensus.DPoS.SideChain.Tests/DPoSSideChainContractTesterExtensions.cs
  AElf.Contracts.Consensus.DPoS.SideChain/ConsensusContract/Process.cs
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Core.Tests/AElf.Core.Tests.csproj
  AElf.CrossChain.Core/Helpers/CrossChainEventHelper.cs
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Cryptography/AElfKeyStore.cs
  AElf.Cryptography/Certificate/RSAKeyPair.cs
  AElf.Cryptography/IKeyStore.cs
  AElf.Kernel.Consensus.DPoS.Tests/DPoSConsensusTestAElfModule.cs
  AElf.Kernel.Consensus.DPoS.Tests/DPoSInformationGenerationServiceTests.cs
  AElf.Kernel.Consensus.DPoS/Application/ConsensusExtraDataProvider.cs
  AElf.Kernel.Consensus.DPoS/Application/ConsensusValidationProvider.cs
  AElf.Kernel.Consensus.Tests/BestChainFoundEventHandlerTests.cs
  AElf.Kernel.Consensus.Tests/ConsensusServiceTests.cs
  AElf.Kernel.Consensus.Tests/ConsensusTestAElfModule.cs
  AElf.Kernel.Consensus.Tests/ConsensusTransactionGeneratorTests.cs
  AElf.Kernel.Core.Tests/SmartContract/Application/BlockchainStateMergingServiceTests.cs
  AElf.Kernel.Core/Blockchain/Application/BlockExtraDataService.cs
  AElf.Kernel.Core/Blockchain/Helpers/GenesisBlockBuilder.cs
  AElf.Kernel.Core/Extensions/LogEventExtensions.cs
  AElf.Kernel.Core/SmartContract/Application/IBlockchainStateMergingService.cs
  AElf.Kernel.SmartContract/Application/ITransactionReadOnlyExecutionService.cs
  AElf.Kernel.SmartContract/MetaData/CallGraph.cs
  AElf.Kernel.SmartContractExecution/MockResourceUsageDetectionService.cs
  AElf.Kernel.Types/Bloom.cs
  AElf.Kernel.Types/StatePath.cs
  AElf.Kernel.Types/Transaction/Transaction.cs
  AElf.OS.Network.Grpc/GrpcUrl.cs
  AElf.OS.Rpc.Net/NetRpcErrorCode.cs
  AElf.Sdk.CSharp/SmartContractBridgeContextExtensions.cs
  AElf.Sdk.CSharp/State/ActionExtensions.cs
  AElf.WebApp.Application.Chain.Tests/AElf.WebApp.Application.Chain.Tests.csproj
  AElf.WebApp.Application.Net.Tests/AElf.WebApp.Application.Net.Tests.csproj
  AElf.WebApp.Application.TestBase/AElf.WebApp.Application.TestBase.csproj
  scripts/test.sh
Labels: review

#1507 Reorg context
  AElf.Contracts.Genesis.Tests/GenesisContractTest.cs
  AElf.Kernel.Core/Infrastructure/StorageKeyExtensions.cs
  AElf.Kernel.SmartContract.Sdk.Abstracts/ISmartContractContext.cs
  AElf.Kernel.SmartContract.Sdk.Abstracts/IStateProvider.cs
  AElf.Kernel.SmartContract.Sdk.Abstracts/ITransactionContext.cs
  AElf.Kernel.SmartContract.Sdk.Abstracts/StateKeyExtensions.cs
  AElf.Kernel.SmartContract.Sdk.Abstracts/StatePathExtensions.cs
  AElf.Kernel.SmartContract.Tests/Application/SmartContractExecutiveServiceTests.cs
  AElf.Kernel.SmartContract.Tests/HostSmartContractBridgeContextTests.cs
  AElf.Kernel.SmartContract/Application/HostSmartContractBridgeContextService.cs
  AElf.Kernel.SmartContract/Application/IHostSmartContractBridgeContextService.cs
  AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  AElf.Kernel.SmartContract/Application/ITransactionExecutingService.cs
  AElf.Kernel.SmartContract/Application/ITransactionReadOnlyExecutionService.cs
  AElf.Kernel.SmartContract/Application/TieredStateCache.cs
  AElf.Kernel.SmartContract/HostSmartContractBridgeContext.cs
  AElf.Kernel.SmartContract/IHostSmartContractBridgeContext.cs
  AElf.Kernel.SmartContract/Infrastructure/IExecutive.cs
  AElf.Kernel.SmartContract/Sdk/CachedStateProvider.cs
  AElf.Kernel.SmartContract/Sdk/ScopedStateProvider.cs
  AElf.Kernel.SmartContract/Sdk/SmartContractContext.cs
  AElf.Kernel.SmartContract/Sdk/StateProviderFactory.cs
  AElf.Kernel.SmartContract/Sdk/TransactionContext.cs
  AElf.Kernel.Types/Chain/IChainContext.cs
  AElf.Runtime.CSharp.Tests/SmartContractRunnerTest.cs
  AElf.Runtime.CSharp/Executive.cs
  AElf.Sdk.CSharp.Tests/ContractTest.cs
  AElf.Sdk.CSharp.Tests/StateTest.cs
  AElf.Sdk.CSharp.Tests/TestContractTests.cs
  AElf.Sdk.CSharp/CSharpSmartContractContext.cs
  AElf.Sdk.CSharp/CSharpSmartContract`_Internal.cs
  AElf.Sdk.CSharp/State/MappedState.cs
  AElf.Sdk.CSharp/State/SingletonState`.cs
  AElf.Sdk.CSharp/State/StateBase.cs
  AElf.Sdk.CSharp/State/StructuredState.cs
  protobuf/kernel.proto
Labels: review

#1467 Feature find lib in network layer
  AElf.Core/ITaskQueue.cs
  AElf.Kernel.Consensus.DPoS.Tests/IrreversibleBlockDiscoveryServiceTests.cs
  AElf.Kernel.Consensus.DPoS/Application/BestChainFoundEventHandler.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSInformationProvider.cs
  AElf.Kernel.Consensus.DPoS/Application/IDPoSInformationProvider.cs
  AElf.Kernel.Consensus.DPoS/Application/IrreversibleBlockDiscoveryService.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsensusAElfModule.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsts.cs
  AElf.Kernel.Core.Tests/Blockchain/Domain/ChainManagerTests.cs
  AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  AElf.Kernel.Core/KernelConsts.cs
  AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  AElf.Kernel/LastIrreversibleBlockJob.cs
  AElf.Kernel/LastIrreversibleBlockJobArgs.cs
  AElf.OS.Consensus.DPos/AElf.OS.Consensus.DPos.csproj
  AElf.OS.Consensus.DPos/DPoSAnnouncementReceivedEventDataHandler.cs
  AElf.OS.Consensus.DPos/DPoSConsensusOSAElfModule.cs
  AElf.OS.Core.Tests/Network/NetworkServiceTests.cs
  AElf.OS.Core/Network/Application/INetworkService.cs
  AElf.OS.Core/Network/Application/NetworkService.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Rpc.Net/NetRpcService.cs
  AElf.OS/AElf.OS.csproj
  AElf.OS/OSAElfModule.cs
  AElf.WebApp.Application.Net/NetAppService.cs
  AElf.WebApp.Application.Net/TestAppService.cs
  AElf.sln
  AElf.sln.DotSettings
Labels: review

#1512 Improve crosschain.
  AElf.CrossChain.Core/Cache/BlockInfoCache.cs
  AElf.CrossChain.Core/Cache/CrossChainDataConsumer.cs
  AElf.CrossChain.Core/Cache/ICrossChainDataConsumer.cs
  AElf.CrossChain.Core/Services/CrossChainDataProvider.cs
  AElf.CrossChain.Core/Services/CrossChainService.cs
  AElf.CrossChain.Core/Services/ICrossChainDataProvider.cs
  AElf.CrossChain.Grpc.Tests/GrpcClientTests.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainClientNodePluginTest.cs
  AElf.CrossChain.Grpc.Tests/GrpcCrossChainTestModule.cs
  AElf.CrossChain.Grpc.Tests/GrpcServerTests.cs
  AElf.CrossChain.Grpc/Grpc/Client/CrossChainGrpcClient.cs
  AElf.CrossChain.Grpc/Grpc/Client/CrossChainGrpcClientController.cs
  AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServer.cs
  AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs
  AElf.CrossChain.Grpc/Grpc/Server/ICrossChainServer.cs
  AElf.CrossChain.Grpc/GrpcCrossChainClientNodePlugin.cs
  AElf.CrossChain.Grpc/GrpcCrossChainConfigOption.cs
  AElf.CrossChain.Grpc/GrpcCrossChainServerNodePlugin.cs
  AElf.CrossChain.Tests/Cache/CrossChainDataConsumerTest.cs
  AElf.CrossChain.Tests/CrossChainDataProviderTest.cs
  AElf.CrossChain.Tests/CrossChainIndexingTransactionGeneratorTest.cs
  AElf.CrossChain.Tests/CrossChainTestModule.cs
  protobuf/header_info.proto
Labels: review

#1499 Replace evil node by other candidate.
  AElf.Consensus.DPoS.Types/ConsensusCommandExtensions.cs
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/AElf.Contracts.Consensus.DPoS.Tests.TestKit.csproj
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/DPoSTestBase.cs
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/GetConsensusCommandTest.cs
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/InValueRecoveryTest.cs
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/MiningProcessTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ElectionTest.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Election.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Helpers.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Initialize.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/NextTerm.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Process.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/UpdateConsensus.cs
  AElf.Contracts.Consensus.DPoS/README.md
  protobuf/consensus_dpos.proto
Labels: review

#1509 Fix execute twice problem
  AElf.Contracts.Consensus.DPoS.Tests.TestKit/MiningProcessTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ContractTesterExtensions.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Kernel.Core/SmartContract/Domain/IBlockchainStateManager.cs
  AElf.Kernel.Core/SmartContract/Infrastructure/StateStore.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.SmartContractExecution/Application/IBlockExecutingService.cs
Labels: review

#1521 Feature PreTransactions
  AElf.Contracts.MultiToken.Tests/MultiTokenContractTest.cs
  AElf.Contracts.MultiToken/TokenContractState.cs
  AElf.Contracts.MultiToken/TokenContract_Actions.cs
  AElf.Contracts.MultiToken/TokenContract_IFeeChargedContract.cs
  AElf.Contracts.TestKit/AElf.Contracts.TestKit.csproj
  AElf.Contracts.TestKit/ContractTestBase.cs
  AElf.Contracts.TestKit/Protobuf/Generated/.gitkeep
  AElf.Contracts.TokenConverter.Tests/AElf.Contracts.TokenConverter.Tests.csproj
  AElf.Contracts.TokenConverter.Tests/TokenConverterTestBase.cs
  AElf.Kernel.Core/EventMessages/UnexecutableTransactionsFoundEvent.cs
  AElf.Kernel.Core/Extensions/TransactionTraceExtensions.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract.csproj
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract/Contract.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract/ContractState.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract/Protobuf/Generated/.gitkeep
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.csproj
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/ExecutionPluginForAcs1Test.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/ExecutionPluginForAcs1TestBase.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/ExecutionPluginForAcs1TestModule.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/Protobuf/Generated/.gitkeep
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.csproj
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/ExecutionPluginForAcs1Module.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/FeeChargeExecutionPlugin.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/MethodStubFactory.cs
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/Protobuf/Generated/.gitkeep
  AElf.Kernel.SmartContract.ExecutionPluginForAcs1/TransactionGeneratingOnlyMethodStubFactory.cs
  AElf.Kernel.SmartContract/Application/IExecutionPlugin.cs
  AElf.Kernel.SmartContract/Application/ITransactionExecutingService.cs
  AElf.Kernel.SmartContract/Infrastructure/IExecutive.cs
  AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  AElf.Kernel.TransactionPool/Application/TxPoolInterestedEventsHandler.cs
  AElf.Kernel.TransactionPool/Infrastructure/ITxHub.cs
  AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  AElf.Kernel.Types/Transaction/TransactionTrace.cs
  AElf.Runtime.CSharp.ExecutiveTokenPlugin/DefaultServiceBinder.cs
  AElf.Runtime.CSharp.ExecutiveTokenPlugin/FeeChargeExecutivePlugin.cs
  AElf.Runtime.CSharp/Executive.cs
  AElf.sln
  protobuf/acs1.proto
  protobuf/acs1_plugin_test_contract.proto
  protobuf/kernel.proto
Labels: review

#1520 Enhancement/verify
  AElf.Blockchains.MainChain/MainChainAElfModule.cs
  AElf.Blockchains.SideChain/SideChainAElfModule.cs
  AElf.Contracts.TestBase/ContractTestAElfModule.cs
  AElf.Contracts.TestBase/ContractTester.cs
  AElf.Cryptography.Tests/AElfKeyStoreTests.cs
  AElf.Kernel.Consensus.DPoS/DPoSOptions.cs
  AElf.Kernel.SmartContractExecution/Application/IBlockAttachService.cs
  AElf.Kernel.TransactionPool.Tests/TransactionPoolTestAElfModule.cs
  AElf.Kernel.TransactionPool.Tests/TxHubTests.cs
  AElf.Kernel.TransactionPool/AElf.Kernel.TransactionPool.csproj
  AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  AElf.Kernel.TransactionPool/TransactionOptions.cs
  AElf.Kernel.TransactionPool/TransactionPoolAElfModule.cs
  AElf.Kernel.TransactionPool/TransactionPoolConsts.cs
  AElf.Launcher/appsettings.json
  AElf.OS.Core/CoreOSAElfModule.cs
  AElf.OS.Core/Network/Application/NetworkService.cs
  AElf.OS.Network.Grpc.Tests/GrpcPeerTests.cs
  AElf.OS.Network.Grpc.Tests/GrpcServerServiceTests.cs
  AElf.OS.Network.Grpc/GrpcPeerPool.cs
  AElf.OS.Network.Grpc/GrpcServerService.cs
  AElf.OS.Tests/AElf.OS.Tests.csproj
  AElf.OS.Tests/Handlers/PeerConnectedEventHandlerTests.cs
  AElf.OS/Handlers/PeerConnectedEventHandler.cs
  AElf.OS/OSConsts.cs
  AElf.TestLauncher/appsettings.json
  AElf.sln
  protobuf/network_types.proto
  protobuf/peer_service.proto
Labels: review

#1522 Feature side chain initialization
  AElf.Blockchains.MainChain/MainChainAElfModule.cs
  AElf.Blockchains.SideChain/SideChainAElfModule.cs
  AElf.Contracts.Consensus.DPoS.SideChain/ConsensusContract/Sidechain.cs
  AElf.Contracts.Consensus.DPoS.SideChain/ContractState/SidechainStates.cs
  AElf.Contracts.Consensus.DPoS.Tests/ViewTest.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/ViewMethods.cs
  AElf.Contracts.CrossChain.Tests/CrossChainContractTestBase.cs
  AElf.Contracts.CrossChain.Tests/CrossChainIndexingActionTest.cs
  AElf.Contracts.CrossChain.Tests/SideChainLifeTimeManagementTest.cs
  AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  AElf.Contracts.CrossChain/CrossChainContract.cs
  AElf.Contracts.CrossChain/CrossChainContractState.cs
  AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  AElf.Contracts.CrossChain/CrossChainContract_View.cs
  AElf.CrossChain.Core/Helpers/ICrossChainContractReader.cs
  AElf.CrossChain.Core/Services/CrossChainBlockExtraDataProvider.cs
  AElf.CrossChain.Core/Services/CrossChainDataProvider.cs
  AElf.CrossChain.Core/Services/CrossChainIndexingTransactionGenerator.cs
  AElf.CrossChain.Core/Services/CrossChainService.cs
  AElf.CrossChain.Core/Services/CrossChainValidationProvider.cs
  AElf.CrossChain.Core/Services/ICrossChainDataProvider.cs
  AElf.CrossChain.Core/Services/ICrossChainService.cs
  AElf.CrossChain.Grpc/Grpc/Client/CrossChainGrpcClient.cs
  AElf.CrossChain.Grpc/Grpc/Client/CrossChainGrpcClientController.cs
  AElf.CrossChain.Grpc/Grpc/Server/CrossChainGrpcServerBase.cs
  AElf.CrossChain.Grpc/GrpcCrossChainAElfModule.cs
  AElf.CrossChain.Grpc/GrpcCrossChainClientNodePlugin.cs
  AElf.CrossChain.Grpc/IChainInitializationPlugin.cs
  AElf.CrossChain.Tests/CrossChainServiceTest.cs
  AElf.Kernel.Consensus.DPoS/Application/DPoSInformationProvider.cs
  AElf.Kernel.Consensus.DPoS/Application/IDPoSInformationProvider.cs
  protobuf/consensus_dpos.proto
  protobuf/cross_chain_contract.proto
  protobuf/crosschain.proto
  protobuf/dpos_contract.proto
  protobuf/dpos_crosschain_state.proto
  protobuf/dpos_sidechain_contract.proto
  protobuf/header_info.proto
Labels: review

#1525 Fix fork problem
  AElf.Kernel.Consensus.DPoS/Application/BestChainFoundEventHandler.cs
  AElf.Kernel.Consensus.DPoS/DPoSConsts.cs
  AElf.Kernel.Core/KernelConsts.cs
  AElf.Kernel.SmartContractExecution/ExecutionConsts.cs
  AElf.Kernel/NewIrreversibleBlockFoundEventHandler.cs
  AElf.Kernel/Services/BlockMiningEventHandler.cs
  AElf.OS.Consensus.DPos/DPoSAnnouncementReceivedEventDataHandler.cs
  AElf.OS.Tests/Jobs/ForkDownloadJobTest.cs
  AElf.OS/Handlers/PeerConnectedEventHandler.cs
  AElf.OS/Jobs/BlockSyncJob.cs
Labels: review

#1508 Improve consensus dpos contract test cases
  AElf.Contracts.Consensus.DPoS.Tests/BasicExtensionsTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ContractTesterExtensions.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/NextTerm.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/ViewMethods.cs
  AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  AElf.Contracts.TokenConverter.Tests/TokenConverterContractTests.cs
  AElf.Contracts.TokenConverter/TokenConverterContract.cs
  AElf.Kernel.Core/SmartContractExecution/Domain/TransactionTraceManager.cs
  AElf.OS.Tests/Account/AccountServiceTests.cs
  protobuf/dpos_contract.proto
Labels: review

#1530 Vote Contract & Election Contract
  AElf.Contracts.Consensus.DPoS.Tests/ConsensusProcessTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ContractTesterExtensions.cs
  AElf.Contracts.Consensus.DPoS.Tests/ElectionTest.cs
  AElf.Contracts.Consensus.DPoS.Tests/ViewTest.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/Election.cs
  AElf.Contracts.Consensus.DPoS/ConsensusContract/ViewMethods.cs
  AElf.Contracts.Dividend/DividendContract.cs
  AElf.Contracts.Dividend/DividendContract_View.cs
  AElf.Contracts.Election/AElf.Contracts.Election.csproj
  AElf.Contracts.Election/ContractsReferences.cs
  AElf.Contracts.Election/ElectionContract.cs
  AElf.Contracts.Election/ElectionContractConsts.cs
  AElf.Contracts.Election/ElectionContractState.cs
  AElf.Contracts.Election/Protobuf/Generated/.gitkeep
  AElf.Contracts.MultiToken/TokenContract_Actions.cs
  AElf.Contracts.Vote/AElf.Contracts.Vote.csproj
  AElf.Contracts.Vote/ContractsReferences.cs
  AElf.Contracts.Vote/Protobuf/Generated/.gitkeep
  AElf.Contracts.Vote/README.md
  AElf.Contracts.Vote/VoteContract.cs
  AElf.Contracts.Vote/VoteContractState.cs
  AElf.Contracts.Vote/VoteExtensions.cs
  AElf.Kernel.Types/AElf.Kernel.Types.csproj
  AElf.sln
  protobuf/election.proto
  protobuf/election_contract.proto
  protobuf/kernel.proto
  protobuf/token_contract.proto
  protobuf/vote.proto
  protobuf/vote_contract.proto
Labels: review

#1426 reorganize documentation
  book.json
  docs/Advanced/CONSENSUS.md
  docs/Advanced/INTEROPERABILITY.md
  docs/Advanced/SCHEDULER.md
  docs/Architecture/architecture.md
  docs/Architecture/implementations.md
  docs/Architecture/introduction.md
  docs/Architecture/node-archi.png
  docs/Contract/archi.md
  docs/Contract/def.md
  docs/Contract/depl.md
  docs/Contract/events.md
  docs/Contract/helloworld.md
  docs/Contract/impl.md
  docs/Contract/intro.md
  docs/Contract/msgs.md
  docs/Contract/service.md
  docs/Contract/upd.md
  docs/Contract/update.md
  docs/Introduction/before.md
  docs/Introduction/quickstart.md
  docs/Protocol/addresses.md
  docs/Protocol/blocks.md
  docs/Protocol/txs.md
  docs/README.md
  docs/RPC/chain.md
  docs/RPC/main.md
  docs/RPC/reference.md
  docs/RPC/wallet.md
  docs/Resources/resources.md
  docs/Resources/walletAndExplorer.md
  docs/SDK/javascript/AElf.md
  docs/SDK/javascript/Wallet.md
  docs/SDK/javascript/js-sdk.md
  docs/WalletAndExplorer/wallet.md
  docs/cli/cli.md
  docs/cli/intro.md
  docs/cli/methods.md
  docs/crosschain/archi.md
  docs/crosschain/intro.md
  docs/crosschain/setup.md
  docs/crosschain/verif.md
  docs/devops/devops.md
  docs/main-structure.md
  docs/multitoken/contract.md
  docs/perf/perf.md
  docs/publicchain/archi.md
  docs/publicchain/auth.md
  docs/publicchain/crosschainmultitok.md
  docs/publicchain/dpos.md
  docs/publicchain/intro.md
  docs/publicchain/multilvlchain.md
  docs/publicchain/resources.md
  docs/tosort/Roadmap.md
  docs/tosort/test.puml
  protobuf/token_contract.proto
  src/AElf.Kernel.SmartContract/HostSmartContractBridgeContext.cs
Labels: review

#1534 Election Contract
  protobuf/vote.proto
  protobuf/vote_contract.proto
  src/AElf.Contracts.Election/ElectionContract.cs
  src/AElf.Contracts.Election/ElectionContractConsts.cs
  src/AElf.Contracts.Vote/AElf.Contracts.Vote.csproj
  src/AElf.Contracts.Vote/ContractsReferences.cs
  src/AElf.Contracts.Vote/README.md
  src/AElf.Contracts.Vote/VoteContract.cs
  src/AElf.Contracts.Vote/VoteContractConsts.cs
  src/AElf.Contracts.Vote/VoteContractState.cs
  src/AElf.Contracts.Vote/VoteExtensions.cs
Labels: review

#1529 Feature/Benchmark
  .gitignore
  AElf.sln
  bench/AElf.Benchmark/AElf.Benchmark.csproj
  bench/AElf.Benchmark/BenchmarkAElfModule.cs
  bench/AElf.Benchmark/BenchmarkTestBase.cs
  bench/AElf.Benchmark/BlockAttachTests.cs
  bench/AElf.Benchmark/BlockExecutingTests.cs
  bench/AElf.Benchmark/BlockchainStateMergingTests.cs
  bench/AElf.Benchmark/MinerTests.cs
  bench/AElf.Benchmark/Program.cs
  bench/AElf.Benchmark/TransactionVerifySignatureTests.cs
  bench/AElf.Benchmark/TxHubHandleBestChainFoundTests.cs
  bench/AElf.Benchmark/TxHubTransactionsReceiveTests.cs
Labels: review

#1532 Improve unit case coverage(will complete on 4.12)
  src/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  src/AElf.Kernel.Core/Extensions/TransactionExtensions.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  src/AElf.Kernel/Services/BlockMiningEventHandler.cs
  src/AElf.OS.Rpc.ChainController/ServiceExtensions.cs
  src/AElf.OS/Jobs/BlockSyncJob.cs
  test/AElf.Contracts.Consensus.DPoS.Tests.TestKit/MiningProcessTest.cs
  test/AElf.Contracts.Consensus.DPoS.Tests/HelperMethodsTest.cs
  test/AElf.Contracts.CrossChain.Tests/CrossChainIndexingActionTest.cs
  test/AElf.Core.Tests/AElf.Core.Tests.csproj
  test/AElf.Kernel.Consensus.Tests/BestChainFoundEventHandlerTests.cs
  test/AElf.Kernel.Consensus.Tests/ConsensusTestAElfModule.cs
  test/AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
Labels: review

#1535 update the readme to reflect current progress.
  README.md
Labels: review

#1543 web api adjustment
  src/AElf.WebApp.Web/UpperCamelCaseNamingStrategy.cs
  src/AElf.WebApp.Web/WebAppAbpServiceConvention.cs
  src/AElf.WebApp.Web/WebWebAppAElfModule.cs
  test/AElf.WebApp.Application.Chain.Tests/ChainAppServiceTest.cs
Labels: review

#1544 Cleanup TestKit dependencies
  AElf.sln
  scripts/deploy_myget.sh
  scripts/deploy_myget_daily.sh
  scripts/deploy_nuget.sh
  src/AElf.Contracts.TestKit/AElf.Contracts.TestKit.csproj
  src/AElf.Contracts.TestKit/ContractTestBase.cs
  src/AElf.Contracts.TestKit/ContractTestModule.cs
  src/AElf.Contracts.TestKit/IBlockTimeProvider.cs
  src/AElf.Contracts.TestKit/IContractTesterFactory.cs
  src/AElf.Contracts.TestKit/IRefBlockInfoProvider.cs
  src/AElf.Contracts.TestKit/ITransactionExecutor.cs
  src/AElf.Contracts.TestKit/MethodStubFactory.cs
  src/AElf.Contracts.TestKit/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.TestKit/SampleECKeyPairs.cs
  src/AElf.Contracts.TestKit/SmartContractTestConstants.cs
  src/AElf.Contracts.TestKit/TransactionExecutor.cs
  test/AElf.Contracts.Consensus.DPoS.Tests.TestKit/AElf.Contracts.Consensus.DPoS.Tests.TestKit.csproj
  test/AElf.Contracts.Consensus.DPoS.Tests/AElf.Contracts.Consensus.DPoS.Tests.csproj
  test/AElf.Contracts.Genesis.Tests/AElf.Contracts.Genesis.Tests.csproj
  test/AElf.Contracts.TokenConverter.Tests/AElf.Contracts.TokenConverter.Tests.csproj
  test/AElf.Kernel.Core.Tests/AElf.Kernel.Core.Tests.csproj
  test/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.csproj
Labels: review

#1546 web api adjustment for `GetTransactionResult`
  src/AElf.WebApp.Application.Chain/Dto/LogEventDto.cs
Labels: review

#1537 Bug fix about evil node key pair finding.
  src/AElf.Contracts.Consensus.DPoS/ConsensusContract/UpdateConsensus.cs
Labels: review

#1545 Improve benchmark
  bench/AElf.Benchmark/BenchmarkAElfModule.cs
  bench/AElf.Benchmark/BlockAttachTests.cs
  bench/AElf.Benchmark/BlockExecutingTests.cs
  bench/AElf.Benchmark/BlockchainStateMergingTests.cs
  bench/AElf.Benchmark/MinerTests.cs
  bench/AElf.Benchmark/TxHubHandleBestChainFoundTests.cs
  bench/AElf.Benchmark/TxHubTransactionsReceiveTests.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
Labels: review

#1564 Improve build without gen package
  AElf.All.sln
  scripts/build.sh
Labels: review

#1567 Fix storage key
  src/AElf.Kernel.Core/Blockchain/Domain/ITransactionBlockIndexManager.cs
  src/AElf.Kernel.Core/Blockchain/Domain/ITransactionResultManager.cs
Labels: review

#1566 Change get block info web api : Get block info by block hash or height
  src/AElf.WebApp.Application.Chain/ChainAppService.cs
  test/AElf.WebApp.Application.Chain.Tests/ChainAppServiceTest.cs
Labels: review

#1565 Vote contract test cases
  .travis.yml
  scripts/upload_coverage.sh
  src/AElf.Contracts.Vote/VoteContract.cs
  test/AElf.Contracts.Vote.Tests/AElf.Contracts.Vote.Tests.csproj
  test/AElf.Contracts.Vote.Tests/VoteContractTestBase.cs
  test/AElf.Contracts.Vote.Tests/VoteTests.cs
  test/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.csproj
Labels: review

#1472 Enable proposal and authorization.
  AElf.sln
  protobuf/acs3.proto
  protobuf/association_auth_contract.proto
  protobuf/auth.proto
  protobuf/authorization_contract.proto
  protobuf/parliament_auth_contract.proto
  protobuf/proposal.proto
  protobuf/referendum_auth_contract.proto
  src/AElf.Blockchains.BasicBaseChain/AElf.Blockchains.BasicBaseChain.csproj
  src/AElf.Contracts.AssociationAuth/AElf.Contracts.AssociationAuth.csproj
  src/AElf.Contracts.AssociationAuth/AssociationAuth.cs
  src/AElf.Contracts.AssociationAuth/AssociationAuthState.cs
  src/AElf.Contracts.AssociationAuth/AssociationAuth_Helper.cs
  src/AElf.Contracts.AssociationAuth/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.Authorization/AElf.Contracts.Authorization.csproj
  src/AElf.Contracts.Authorization/AuthorizationContract.cs
  src/AElf.Contracts.Authorization/AuthorizationContractState.cs
  src/AElf.Contracts.Authorization/AuthorizationContract_Helper.cs
  src/AElf.Contracts.Authorization/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  src/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  src/AElf.Contracts.ParliamentAuth/AElf.Contracts.ParliamentAuth.csproj
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuthState.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth_Helper.cs
  src/AElf.Contracts.ParliamentAuth/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.Proposal/AElf.Contracts.Proposal.csproj
  src/AElf.Contracts.Proposal/ProposalContract.cs
  src/AElf.Contracts.Proposal/ProposalContractState.cs
  src/AElf.Contracts.Proposal/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.ReferendumAuth/AElf.Contracts.ReferendumAuth.csproj
  src/AElf.Contracts.ReferendumAuth/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.ReferendumAuth/ReferencedunAuth.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuthState.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuth_Helper.cs
  src/AElf.CrossChain.Core/Cache/ICrossChainDataConsumer.cs
  src/AElf.CrossChain.Core/Services/LocalLibService.cs
  src/AElf.Kernel.Consensus.DPoS/AElf.Kernel.Consensus.DPoS.csproj
  src/AElf.Kernel.Types/AElf.Kernel.Types.csproj
  src/AElf.Kernel.Types/Proposal/Proposal.cs
  test/AElf.Contracts.TestBase/AElf.Contracts.TestBase.csproj
  test/AElf.Contracts.TestBase/ContractTester.cs
  test/AElf.Kernel.Types.Tests/AElf.Kernel.Types.Tests.csproj
  test/AElf.Kernel.Types.Tests/Proposal/ProposalTests.cs
Labels: review

#1568 consensus documentation
  docs/publicchain/dpos.md
Labels: review

#1577 Improve unit test cases
  scripts/test.sh
  src/AElf.OS.Core/Network/Events/PeerConnectedEventData.cs
  src/AElf.OS.Core/Node/Application/IOsBlockchainNodeContextService.cs
  src/AElf.OS.Network.Grpc/GrpcServerService.cs
  src/AElf.OS/Handlers/PeerConnectedEventHandler.cs
  test/AElf.Contracts.MultiToken.Tests/LockTest.cs
  test/AElf.Kernel.SmartContractExecution.Tests/ContractTest.cs
  test/AElf.OS.Network.Grpc.Tests/GrpcPeerPoolTests.cs
  test/AElf.OS.Tests/AElf.OS.Tests.csproj
  test/AElf.OS.Tests/Jobs/BlockSyncJobTest.cs
  test/AElf.WebApp.Application.Net.Tests/AElf.WebApp.Application.Net.Tests.csproj
Labels: review

#1578 Fix node restart problem
  src/AElf.Kernel.Node/Application/IBlockchainNodeContextService.cs
  test/AElf.Contracts.TestBase/ContractTestAElfModule.cs
Labels: review

#1569 Fix issues about consensus
  src/AElf.Contracts.Consensus.DPoS/ConsensusContract/UpdateConsensus.cs
Labels: review

#1582 Web api adjustment
  Test/AElf.WebApp.Application.Chain.Tests/BlockChainAppServiceTest.cs
  src/AElf.WebApp.Application.Chain/AElf.WebApp.Application.Chain.csproj
  src/AElf.WebApp.Application.Chain/BlockChainAppService.cs
  src/AElf.WebApp.Application.Chain/Dto/ChainStatusDto.cs
  src/AElf.WebApp.Application.Chain/Dto/ParamsDto.cs
  src/AElf.WebApp.Application.Chain/VersionTestAppService.cs
  src/AElf.WebApp.Application.Net/AElf.WebApp.Application.Net.csproj
  src/AElf.WebApp.Application.Net/NetAppService.cs
  src/AElf.WebApp.Web/ConfigureSwaggerOptions.cs
  test/AElf.WebApp.Application.Chain.Tests/VersionTestAppServiceTest.cs
  test/AElf.WebApp.Application.Net.Tests/AElf.WebApp.Application.Net.Tests.csproj
Labels: review

#1591 Improve authorization.
  AElf.sln
  protobuf/acs3.proto
  protobuf/association_auth_contract.proto
  protobuf/parliament_auth_contract.proto
  protobuf/referendum_auth_contract.proto
  src/AElf.Contracts.AssociationAuth/AElf.Contracts.AssociationAuth.csproj
  src/AElf.Contracts.AssociationAuth/AssociationAuth.cs
  src/AElf.Contracts.AssociationAuth/AssociationAuthState.cs
  src/AElf.Contracts.AssociationAuth/AssociationAuth_Helper.cs
  src/AElf.Contracts.ParliamentAuth/AElf.Contracts.ParliamentAuth.csproj
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuthState.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth_Helper.cs
  src/AElf.Contracts.Proposal/AElf.Contracts.Proposal.csproj
  src/AElf.Contracts.Proposal/ProposalContract.cs
  src/AElf.Contracts.Proposal/ProposalContractState.cs
  src/AElf.Contracts.Proposal/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.ReferendumAuth/AElf.Contracts.ReferendumAuth.csproj
  src/AElf.Contracts.ReferendumAuth/ReferencedunAuth.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuthState.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuth_Helper.cs
Labels: review

#1592 Improve packages
  AElf.All.sln
  src/AElf.Consensus.DPoS.Types/AElf.Consensus.DPoS.Types.csproj
  src/AElf.Contracts.AssociationAuth/AElf.Contracts.AssociationAuth.csproj
  src/AElf.Contracts.Consensus.DPoS.SideChain/AElf.Contracts.Consensus.DPoS.SideChain.csproj
  src/AElf.Contracts.Consensus.DPoS/AElf.Contracts.Consensus.DPoS.csproj
  src/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  src/AElf.Contracts.Dividend/AElf.Contracts.Dividend.csproj
  src/AElf.Contracts.Election/AElf.Contracts.Election.csproj
  src/AElf.Contracts.Genesis/AElf.Contracts.Genesis.csproj
  src/AElf.Contracts.MultiToken/AElf.Contracts.MultiToken.csproj
  src/AElf.Contracts.ParliamentAuth/AElf.Contracts.ParliamentAuth.csproj
  src/AElf.Contracts.Proposal/AElf.Contracts.Proposal.csproj
  src/AElf.Contracts.ReferendumAuth/AElf.Contracts.ReferendumAuth.csproj
  src/AElf.Contracts.Resource.FeeReceiver/AElf.Contracts.Resource.FeeReceiver.csproj
  src/AElf.Contracts.Resource/AElf.Contracts.Resource.csproj
  src/AElf.Contracts.TestKit/AElf.Contracts.TestKit.csproj
  src/AElf.Contracts.TokenConverter/AElf.Contracts.TokenConverter.csproj
  src/AElf.Contracts.Vote/AElf.Contracts.Vote.csproj
  src/AElf.CrossChain.Grpc/AElf.CrossChain.Grpc.csproj
  src/AElf.CrossChain.Types/AElf.CrossChain.Types.csproj
  src/AElf.Kernel.SmartContract.ExecutionPluginForAcs1/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.csproj
  src/AElf.Kernel.SmartContractExecution/AElf.Kernel.SmartContractExecution.csproj
  src/AElf.Kernel.Types/AElf.Kernel.Types.csproj
  src/AElf.OS.Consensus.DPos/AElf.OS.Consensus.DPos.csproj
  src/AElf.OS.Core/AElf.OS.Core.csproj
  src/AElf.Runtime.CSharp.ExecutiveTokenPlugin/AElf.Runtime.CSharp.ExecutiveTokenPlugin.csproj
  src/AElf.Runtime.CSharp/AElf.Runtime.CSharp.csproj
  src/AElf.Types/AElf.Types.csproj
  src/AElf.WebApp.Application.Chain/AElf.WebApp.Application.Chain.csproj
  src/AElf.WebApp.Application.Core/AElf.WebApp.Application.Core.csproj
  src/AElf.WebApp.Application.Net/AElf.WebApp.Application.Net.csproj
  src/AElf.WebApp.Web/AElf.WebApp.Web.csproj
  test/AElf.Contracts.Consensus.DPoS.Tests.TestKit/AElf.Contracts.Consensus.DPoS.Tests.TestKit.csproj
  test/AElf.Contracts.Genesis.Tests/AElf.Contracts.Genesis.Tests.csproj
  test/AElf.Contracts.TokenConverter.Tests/AElf.Contracts.TokenConverter.Tests.csproj
  test/AElf.Contracts.Vote.Tests/AElf.Contracts.Vote.Tests.csproj
  test/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.TestContract.csproj
  test/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests.csproj
  test/AElf.Runtime.CSharp.Tests.TestContract/AElf.Runtime.CSharp.Tests.TestContract.csproj
Labels: review

#1557 Feature/Startup config
  src/AElf.Blockchains.BasicBaseChain/BasicBaseChainAElfModule.cs
  src/AElf.Blockchains.BasicBaseChain/TokenInitialOptions.cs
  src/AElf.Blockchains.MainChain/MainChainAElfModule.cs
  src/AElf.Contracts.Consensus.DPoS/ConsensusContract/Election.cs
  src/AElf.Contracts.Consensus.DPoS/ConsensusContract/Initialize.cs
  src/AElf.Contracts.Consensus.DPoS/ContractState/DPoSStates.cs
  src/AElf.Contracts.CrossChain/CrossChainContract.cs
  src/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  src/AElf.Contracts.Dividend/DividendContract.cs
  src/AElf.Contracts.Election/ElectionContract.cs
  src/AElf.Contracts.Election/ElectionContractConsts.cs
  src/AElf.Contracts.Resource.FeeReceiver/FeeReceiverContract.cs
  src/AElf.Contracts.Resource/ResourceContract.cs
  src/AElf.Contracts.TestKit/ContractTestModule.cs
  src/AElf.Cryptography/AElfKeyStore.cs
  src/AElf.Kernel.Consensus.DPoS/DPoSConsensusAElfModule.cs
  src/AElf.Kernel.SmartContract.Sdk.Abstracts/ISmartContractBridgeContext.cs
  src/AElf.Kernel.SmartContract/HostSmartContractBridgeContext.cs
  src/AElf.Kernel.Types/AElf.Kernel.Types.csproj
  src/AElf.Launcher/AElf.Launcher.csproj
  src/AElf.Launcher/Startup.cs
  src/AElf.Launcher/appsettings.MainChain.CustomNet.json
  src/AElf.Launcher/appsettings.MainChain.MainNet.json
  src/AElf.Launcher/appsettings.MainChain.TestNet.json
  src/AElf.Launcher/appsettings.json
  src/AElf.OS/OSAElfModule.cs
  src/AElf.Sdk.CSharp/CSharpSmartContractContext.cs
  test/AElf.Contracts.Consensus.DPoS.Tests.TestKit/DPoSTestBase.cs
  test/AElf.Contracts.TestBase/ContractTester.cs
  test/AElf.Kernel.SmartContract.Tests/SmartContractTestAElfModule.cs
Labels: review

#1598 docs alpha release
  docs/Architecture/architecture.md
  docs/Architecture/implementations.md
  docs/Architecture/introduction.md
  docs/Contract/archi.md
  docs/Contract/sc-as-service.png
  docs/Introduction/before.md
  docs/Introduction/config.md
  docs/Introduction/quickstart.md
  docs/Resources/browserExtension.md
  docs/Resources/resources.md
  docs/Web/main.md
  docs/main-structure.md
  docs/publicchain/archi.md
  docs/publicchain/auth.md
  docs/publicchain/crosschainmultitok.md
  docs/publicchain/intro.md
  docs/publicchain/multilvlchain.md
  docs/publicchain/resources.md
  docs/tutorials/dapp/browserExtension.md
  docs/tutorials/dapp/dep-yes.png
  docs/tutorials/dapp/jssdk.md
  docs/tutorials/dapp/main.md
  docs/tutorials/dapp/save_smartContractHelloWorld.md
  docs/tutorials/dapp/setup.md
  docs/tutorials/dapp/smartContractHelloWorld.md
  docs/tutorials/dapp/term.png
  docs/tutorials/enterprise.md
  docs/tutorials/main.md
  docs/tutorials/privateChain.md
Labels: review

#1585 Improve documentation
  docs/Contract/interface.md
  docs/Contract/intro.md
Labels: review

#1599 Fix test folder issue
  Test/AElf.Contracts.Consensus.DPoS.Tests.TestKit/DPoSTestBase.cs
  Test/AElf.Contracts.Profit.Tests/AElf.Contracts.Profit.Tests.csproj
  Test/AElf.Contracts.Profit.Tests/ProfitContractTestAElfModule.cs
  Test/AElf.Contracts.Profit.Tests/ProfitContractTestBase.cs
  Test/AElf.Contracts.Profit.Tests/ProfitTests.cs
  Test/AElf.Contracts.Profit.Tests/Protobuf/Generated/.gitkeep
  Test/AElf.Contracts.TestBase/ContractTester.cs
  Test/AElf.Contracts.Vote.Tests/AElf.Contracts.Vote.Tests.csproj
  src/AElf.Blockchains.MainChain/MainChainAElfModule.cs
  src/AElf.Contracts.Authorization/AuthorizationContract.cs
  src/AElf.Contracts.Proposal/AElf.Contracts.Proposal.csproj
  test/AElf.WebApp.Application.Chain.Tests/BlockChainAppServiceTest.cs
Labels: review

#1605 Fix test folder name
  test/AElf.Contracts.TestContract.Tests/ContractMethodTests.cs
Labels: review

#1606 Fix failed test case
  src/AElf.Contracts.TestContract.Basic1/Basic1Contract_Action.cs
  test/AElf.Contracts.Election.Tests/ElectionContractTestBase.cs
  test/AElf.Contracts.Election.Tests/ElectionTests.cs
  test/AElf.Contracts.TestContract.Tests/ContractMethodTests.cs
Labels: review

#1602 add some navigation links and intro page to improve navigation
  README.md
  book.json
  docs/Architecture/architecture.md
  docs/Architecture/main.md
  docs/Contract/main.md
  docs/Introduction/main.md
  docs/Protocol/main.md
  docs/README.md
  docs/crosschain/main.md
  docs/introduction.md
  docs/main-structure.md
  docs/publicchain/main.md
Labels: review

#1595 [WIP] Side chain lifetime management.
  protobuf/cross_chain_contract.proto
  protobuf/parliament_auth_contract.proto
  protobuf/proposal.proto
  src/AElf.Blockchains.MainChain/AElf.Blockchains.MainChain.csproj
  src/AElf.Blockchains.MainChain/MainChainAElfModule.cs
  src/AElf.Blockchains.SideChain/AElf.Blockchains.SideChain.csproj
  src/AElf.Blockchains.SideChain/SideChainAElfModule.cs
  src/AElf.CLI/yarn.lock
  src/AElf.Contracts.AssociationAuth/AElf.Contracts.AssociationAuth.csproj
  src/AElf.Contracts.AssociationAuth/AssociationAuth.cs
  src/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  src/AElf.Contracts.CrossChain/CrossChainContract.cs
  src/AElf.Contracts.CrossChain/CrossChainContractState.cs
  src/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  src/AElf.Contracts.CrossChain/CrossChainReferenceState.cs
  src/AElf.Contracts.ParliamentAuth/AElf.Contracts.ParliamentAuth.csproj
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuthState.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth_Helper.cs
  src/AElf.Contracts.ReferendumAuth/AElf.Contracts.ReferendumAuth.csproj
  src/AElf.Contracts.ReferendumAuth/ReferencedunAuth.cs
  src/AElf.Kernel/ParliamentAuthContractAddressNameProvider.cs
  src/AElf.Management.Website/Properties/launchSettings.json
  test/AElf.Contracts.CrossChain.Tests/CrossChainContractTestBase.cs
  test/AElf.Contracts.CrossChain.Tests/CrossChainContractTestHelper.cs
  test/AElf.Contracts.CrossChain.Tests/SideChainLifeTimeManagementTest.cs
  test/AElf.Contracts.TestBase/AElf.Contracts.TestBase.csproj
  test/AElf.Contracts.TestBase/ContractTestAElfModule.cs
  test/AElf.Contracts.TestBase/ContractTester.cs
Labels: review

#1597 [WIP] Add some performance test
  AElf.sln
  bench/AElf.Benchmark.PerformanceTestContract/AElf.Benchmark.PerformanceTestContract.csproj
  bench/AElf.Benchmark.PerformanceTestContract/PerformanceTestContract.cs
  bench/AElf.Benchmark.PerformanceTestContract/PerformanceTestContractState.cs
  bench/AElf.Benchmark.PerformanceTestContract/Protobuf/Generated/.gitkeep
  bench/AElf.Benchmark/AElf.Benchmark.csproj
  bench/AElf.Benchmark/BenchmarkAElfModule.cs
  bench/AElf.Benchmark/Fibonacci16Tests.cs
  bench/AElf.Benchmark/LoopDivAdd10MTests.cs
  bench/AElf.Benchmark/LoopExpNop1MTests.cs
  protobuf/performance_test_contract.proto
  test/AElf.OS.TestBase/OSTestHelper.cs
Labels: review

#1607 Test cases for Profit Contract.
  src/AElf.Contracts.Profit/ProfitContract.cs
  src/AElf.Contracts.Profit/ProfitContractConsts.cs
  test/AElf.Contracts.Profit.Tests/ProfitContractTestBase.cs
  test/AElf.Contracts.Profit.Tests/ProfitTests.cs
Labels: review

#1612 Update .travis.yml
  .travis.yml
Labels: review

#1610 Improved dApp tutorial user-friendliness.
  docs/tutorials/dapp/main.md
  docs/tutorials/dapp/setup.md
  docs/tutorials/dapp/smartContractHelloWorld.md
Labels: docs, review

#1613 Remove random number in contract
  AElf.sln
  protobuf/test_basic_function_contract.proto
  protobuf/test_basic_security_contract.proto
  protobuf/test_basic_update_contract.proto
  scripts/test.sh
  src/AElf.Contracts.TestContract.Basic2/ContractReference.cs
  src/AElf.Contracts.TestContract.BasicFunction/AElf.Contracts.TestContract.BasicFunction.csproj
  src/AElf.Contracts.TestContract.BasicFunction/BasicContractState.cs
  src/AElf.Contracts.TestContract.BasicFunction/BasicContract_Action.cs
  src/AElf.Contracts.TestContract.BasicFunction/BasicContract_View.cs
  src/AElf.Contracts.TestContract.BasicFunction/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.TestContract.BasicSecurity/AElf.Contracts.TestContract.BasicSecurity.csproj
  src/AElf.Contracts.TestContract.BasicSecurity/BasicContractState.cs
  src/AElf.Contracts.TestContract.BasicSecurity/BasicContract_Action.cs
  src/AElf.Contracts.TestContract.BasicSecurity/BasicContract_View.cs
  src/AElf.Contracts.TestContract.BasicSecurity/ContractReference.cs
  src/AElf.Contracts.TestContract.BasicSecurity/Protobuf/Generated/.gitkeep
  src/AElf.Contracts.TestContract.BasicUpdate/AElf.Contracts.TestContract.BasicUpdate.csproj
  src/AElf.Contracts.TestContract.BasicUpdate/BasicContractState.cs
  src/AElf.Contracts.TestContract.BasicUpdate/BasicContract_Action.cs
  src/AElf.Contracts.TestContract.BasicUpdate/BasicContract_View.cs
  src/AElf.Contracts.TestContract.BasicUpdate/Protobuf/Generated/.gitkeep
  src/AElf.Launcher/appsettings.json
  test/AElf.Contracts.Election.Tests/ElectionTests.cs
  test/AElf.Contracts.TestContract.Tests/AElf.Contracts.TestContract.Tests.csproj
  test/AElf.Contracts.TestContract.Tests/ContractBasicTests.cs
  test/AElf.Contracts.TestContract.Tests/ContractExternalCallTests.cs
  test/AElf.Contracts.TestContract.Tests/ContractMethodTests.cs
  test/AElf.Contracts.TestContract.Tests/ContractSecurityTests.cs
  test/AElf.Contracts.TestContract.Tests/TestContractTestBase.cs
Labels: review

#1617 Change address to 32 bytes
  src/AElf.Contracts.Genesis/BasicContractZero.cs
  src/AElf.Kernel.Core/Blockchain/Infrastructure/IStaticChainInformationProvider.cs
  src/AElf.Types/Address.cs
  src/AElf.Types/TypeConsts.cs
  test/AElf.Types.Tests/AddressTest.cs
Labels: review

#1618 update setup instructions
  docs/tutorials/dapp/main.md
  docs/tutorials/dapp/setup.md
Labels: docs, review

#1574 Add more verification item
  protobuf/kernel.proto
  src/AElf.Contracts.TestKit/Account.cs
  src/AElf.Contracts.TestKit/ContractTestModule.cs
  src/AElf.Contracts.TestKit/TransactionExecutor.cs
  src/AElf.CrossChain.Core/Services/CrossChainValidationProvider.cs
  src/AElf.Cryptography/CryptoHelpers.cs
  src/AElf.Kernel.ChainController/Application/ChainCreationService.cs
  src/AElf.Kernel.Consensus.DPoS/Application/ConsensusValidationProvider.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockValidationProvider.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockValidationService.cs
  src/AElf.Kernel.Core/Extensions/BlockExtensions.cs
  src/AElf.Kernel.Core/Extensions/TransactionExtensions.cs
  src/AElf.Kernel.Core/KernelConsts.cs
  src/AElf.Kernel.SmartContractExecution/Application/IBlockAttachService.cs
  src/AElf.Kernel/Services/MinerService.cs
  src/AElf.OS/Account/AccountService.cs
  src/AElf.OS/Handlers/PeerConnectedEventHandler.cs
  src/AElf.OS/OSConsts.cs
  test/AElf.Kernel.Consensus.DPoS.Tests/ConsensusValidationProviderTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/BlockValidationProviderTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Domain/TransactionManagerTests.cs
  test/AElf.Kernel.Core.Tests/TransactionPool/Domain/TransactionReceiptManagerTests.cs
  test/AElf.Kernel.SmartContractExecution.Tests/ResourceUsageDetectionServiceTests.cs
  test/AElf.OS.Core.Tests/OSCoreWithChainTestAElfModule.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
Labels: review

#1596 Add authorization test
  AElf.sln
  protobuf/acs3.proto
  src/AElf.Contracts.AssociationAuth/AssociationAuth.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth.cs
  src/AElf.Contracts.ParliamentAuth/ParliamentAuth_Helper.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuth.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuthState.cs
  src/AElf.Contracts.ReferendumAuth/ReferendumAuth_Helper.cs
  test/AElf.Contracts.AssociationAuth.Tests/AElf.Contracts.AssociationAuth.Tests.csproj
  test/AElf.Contracts.AssociationAuth.Tests/AssociationAuthContractTestAElfModule.cs
  test/AElf.Contracts.AssociationAuth.Tests/AssociationAuthContractTestBase.cs
  test/AElf.Contracts.AssociationAuth.Tests/AssociationAuthTests.cs
  test/AElf.Contracts.AssociationAuth.Tests/Protobuf/Generated/.gitkeep
  test/AElf.Contracts.ParliamentAuth.Tests/AElf.Contracts.ParliamentAuth.Tests.csproj
  test/AElf.Contracts.ParliamentAuth.Tests/ParliamentAuthContractTest.cs
  test/AElf.Contracts.ParliamentAuth.Tests/ParliamentAuthContractTestAElfModule.cs
  test/AElf.Contracts.ParliamentAuth.Tests/ParliamentAuthContractTestBase.cs
  test/AElf.Contracts.ParliamentAuth.Tests/Protobuf/Generated/.gitkeep
  test/AElf.Contracts.ReferendumAuth.Tests/AElf.Contracts.ReferendumAuth.Tests.csproj
  test/AElf.Contracts.ReferendumAuth.Tests/Protobuf/Generated/.gitkeep
  test/AElf.Contracts.ReferendumAuth.Tests/ReferendumAuthContractTest.cs
  test/AElf.Contracts.ReferendumAuth.Tests/ReferendumAuthContractTestAElfModule.cs
  test/AElf.Contracts.ReferendumAuth.Tests/ReferendumAuthContractTestBase.cs
Labels: review

#1615 Fix contract update
  src/AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs
  src/AElf.Kernel.SmartContract/Application/SmartContractService.cs
  src/AElf.Kernel.SmartContract/Infrastructure/IExecutive.cs
  src/AElf.Runtime.CSharp/Executive.cs
  src/AElf.Runtime.CSharp/SmartContractRunnerForCategoryZero.cs
  test/AElf.Contracts.TestContract.Tests/ContractBasicTests.cs
Labels: review

#1622 boilerplate: add method to contract guide
  docs/tutorials/dapp/aelf-root.png
  docs/tutorials/dapp/dep-yes.png
  docs/tutorials/dapp/setup.md
  docs/tutorials/dapp/smartContractHelloWorld.md
  docs/tutorials/dapp/vscode-dep.png
Labels: docs

#1611 side chain documentation improvements.
  docs/crosschain/archi-node.png
  docs/crosschain/archi-topology.png
  docs/crosschain/archi.md
  docs/crosschain/intro-topology.png
  docs/crosschain/intro.md
  docs/crosschain/setup.md
  docs/crosschain/side-chain-nodes.png
  docs/crosschain/verif.md
Labels: docs, review
