Repository AElfProject/AElf, pull requests merged in 2019-07, with the labels that each got.

#1864 Cache hash in transaction and block header
  AElf.sln
  bench/AElf.Benchmark/BlockAttachTests.cs
  bench/AElf.Benchmark/BlockExecutingParallelGroupsTests.cs
  bench/AElf.Benchmark/BlockExecutingParallelTests.cs
  bench/AElf.Benchmark/BlockExecutingTests.cs
  bench/AElf.Benchmark/BlockchainStateMergingTests.cs
  bench/AElf.Benchmark/MinerTests.cs
  bench/AElf.Kernel.SmartContractExecution.Benches/BlockExecutingTests.cs
  src/AElf.Kernel.Core/Blockchain/Helpers/GenesisBlockBuilder.cs
  src/AElf.Kernel.Core/Extensions/BlockExtensions.cs
  src/AElf.Kernel.Core/Extensions/BlockHeaderExtensions.cs
  src/AElf.Kernel.Core/Extensions/TransactionExtensions.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.Kernel.Types/Block/Block.cs
  src/AElf.Kernel.Types/Block/BlockBody.cs
  src/AElf.Kernel.Types/Block/BlockHeader.cs
  src/AElf.Types/Types/Transaction.cs
  test/AElf.CrossChain.Communication.Grpc.Tests/GrpcCrossChainServerTestModule.cs
  test/AElf.CrossChain.Communication.Grpc.Tests/LocalLibExtensionTest.cs
  test/AElf.CrossChain.Tests/CrossChainValidationProviderTest.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/BlockValidationProviderTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/FullBlockchainServiceCreateChainTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/TransactionResultServiceTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Domain/BlockChainHelperTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Domain/BlockManagerTests.cs
  test/AElf.Kernel.SmartContract.Tests/HostSmartContractBridgeContextTests.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutingServiceTests.cs
  test/AElf.Kernel.TestBase/KernelTestHelper.cs
  test/AElf.Kernel.Tests/TestBlockExecutingService.cs
  test/AElf.Kernel.Types.Tests/Block/BlockTests.cs
  test/AElf.OS.Core.Tests/AElf.OS.Core.Tests.csproj
  test/AElf.OS.Core.Tests/Network/NetworkServiceTestModule.cs
  test/AElf.OS.Core.Tests/Network/NetworkServiceTests.cs
  test/AElf.OS.Core.Tests/OSCoreTestAElfModule.cs
  test/AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
  test/AElf.OS.Tests/AElf.OS.Tests.csproj
  test/AElf.OS.Tests/BlockSyncForkedTestAElfModule.cs
  test/AElf.OS.Tests/BlockSyncTestAElfModule.cs
  test/AElf.Sdk.CSharp.Tests/SerializationHelperTests.cs
  test/AElf.Test.Helpers/AElf.Test.Helpers.csproj
  test/AElf.Test.Helpers/ChainGenerationHelpers.cs
  test/AElf.WebApp.Application.Chain.Tests/BlockChainAppServiceTest.cs
Labels: review

#1816 Refactor BlockChainAppService
  src/AElf.WebApp.Application.Chain/BlockChainAppService.cs
  src/AElf.WebApp.Application.Chain/BlockchainServiceExtensions.cs
  src/AElf.WebApp.Application.Chain/ChainStatusAppService.cs
  src/AElf.WebApp.Application.Chain/ContractFileDescriptorSetAppService.cs
  src/AElf.WebApp.Application.Chain/ContractMethodDescriptorHelper.cs
  src/AElf.WebApp.Application.Chain/TaskQueueStatusAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionResultAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionResultProxyService.cs
  src/AElf.WebApp.Web/WebAppAbpServiceConvention.cs
Labels: review

#1884 proto formatting
  protobuf/acs1.proto
  protobuf/bad_contract.proto
  protobuf/crosschain.proto
  protobuf/performance_test_contract.proto
  protobuf/resource.proto
  protobuf/resource_contract.proto
  protobuf/test_basic.proto
  protobuf/test_basic_function_contract.proto
  protobuf/test_basic_security_contract.proto
  protobuf/test_basic_update_contract.proto
  protobuf/test_contract.proto
Labels: Approved, review

#1880 Fix NextRound method for side chain.
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_HelpMethods.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_LIB.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_ViewMethods.cs
  src/AElf.Kernel.Core/Blockchain/Application/BlockGenerationService.cs
Labels: review

#1894 Fix failing to open swagger page
  src/AElf.WebApp.Application.Chain/ChainStatusAppService.cs
  src/AElf.WebApp.Application.Chain/ContractFileDescriptorSetAppService.cs
  src/AElf.WebApp.Application.Chain/TaskQueueStatusAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionResultAppService.cs
  src/AElf.WebApp.Web/WebWebAppAElfModule.cs
Labels: review

#1814 Improve block sync
  src/AElf.OS/BlockSync/Application/BlockDownloadService.cs
  src/AElf.OS/BlockSync/Application/BlockFetchService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncAttachService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncQueueService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncValidationService.cs
  src/AElf.OS/BlockSync/Application/IBlockDownloadService.cs
  src/AElf.OS/BlockSync/Application/IBlockFetchService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncAttachService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncQueueService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncValidationService.cs
  src/AElf.OS/BlockSync/BlockSyncConstants.cs
  src/AElf.OS/BlockSync/Dto/SyncAnnouncementDto.cs
  src/AElf.OS/BlockSync/Infrastructure/AnnouncementCacheProvider.cs
  src/AElf.OS/BlockSync/Infrastructure/BlockSyncStateProvider.cs
  src/AElf.OS/BlockSync/Infrastructure/IAnnouncementCacheProvider.cs
  src/AElf.OS/BlockSync/Infrastructure/IBlockSyncStateProvider.cs
  src/AElf.OS/Handlers/AnnouncementReceivedEventHandler.cs
  src/AElf.OS/Handlers/BlockAcceptedEventHandler.cs
  src/AElf.OS/OSAElfModule.cs
  src/AElf.OS/OSConstants.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockDownloadServiceTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncServiceForkedTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncServiceTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncValidationServiceTests.cs
  test/AElf.OS.Tests/BlockSyncForkedTestAElfModule.cs
  test/AElf.OS.Tests/BlockSyncTestAElfModule.cs
  test/AElf.OS.Tests/Handlers/PeerConnectedEventHandlerTests.cs
Labels: review

#1904 Fix service duplicated register
  bench/AElf.BenchBase/BenchBaseAElfModule.cs
  src/AElf.Blockchains.BasicBaseChain/BasicBaseChainAElfModule.cs
  src/AElf.Blockchains.MainChain/MainChainAElfModule.cs
  src/AElf.Blockchains.SideChain/SideChainAElfModule.cs
  src/AElf.Cluster/ClusterAElfModule.cs
  src/AElf.Core/AElfDefaultConventionalRegistrar.cs
  src/AElf.CrossChain.Core/CrossChainAElfModule.cs
  src/AElf.Kernel.BlockTransactionLimitController/BlockTransactionLimitControllerModule.cs
  src/AElf.Kernel.ChainController/ChainControllerAElfModule.cs
  src/AElf.Kernel.Consensus.AEDPoS/AEDPoSAElfModule.cs
  src/AElf.Kernel.Core/AElfKernelConventionalRegistrar.cs
  src/AElf.Kernel.Core/CoreKernelAElfModule.cs
  src/AElf.Kernel.Node/NodeAElfModule.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForAcs1/ExecutionPluginForAcs1Module.cs
  src/AElf.Kernel.SmartContract.Parallel/ParallelExecutionModule.cs
  src/AElf.Kernel.SmartContract/SmartContractAElfModule.cs
  src/AElf.Kernel.SmartContractExecution/SmartContractExecutionAElfModule.cs
  src/AElf.Kernel.Token/TokenKernelAElfModule.cs
  src/AElf.Kernel/KernelAElfModule.cs
  src/AElf.OS.Consensus.DPos/AElfConsensusOSAElfModule.cs
  src/AElf.OS.Core/CoreOSAElfModule.cs
  src/AElf.OS.Rpc.ChainController/ChainControllerRpcModule.cs
  src/AElf.OS.Rpc.Net/NetRpcAElfModule.cs
  src/AElf.OS/OSAElfModule.cs
  src/AElf.Runtime.CSharp.ExecutiveTokenPlugin/ExecutiveTokenPluginCSharpRuntimeAElfModule.cs
  src/AElf.WebApp.Application.Chain/ChainApplicationWebAppAElfModule.cs
  src/AElf.WebApp.Application.Core/CoreApplicationWebAppAElfModule.cs
  src/AElf.WebApp.Application.Net/NetApplicationWebAppAElfModule.cs
  src/AElf.WebApp.Web/WebAppAbpAspNetCoreMvcModule.cs
  src/AElf.WebApp.Web/WebWebAppAElfModule.cs
  test/AElf.Contracts.AssociationAuth.Tests/AssociationAuthContractTestAElfModule.cs
  test/AElf.Contracts.MultiToken.Tests/MultiTokenContractTestAElfModule.cs
  test/AElf.Contracts.Profit.Tests/ProfitContractTestAElfModule.cs
  test/AElf.Contracts.Resource.FeeReceiver.Tests/FeeReceiverContractTestAElfModule.cs
  test/AElf.Contracts.TestBase.Tests/TestBaseTestAElfModule.cs
  test/AElf.Contracts.TestContract.Tests/TestContractAElfModule.cs
  test/AElf.Contracts.TokenConverter.Tests/TokenConverterTestModule.cs
  test/AElf.Contracts.Vote.Tests/VoteContractTestAElfModule.cs
  test/AElf.Core.Tests/Providers/ATestProvider.cs
  test/AElf.Core.Tests/Providers/BTestProvider.cs
  test/AElf.Core.Tests/Providers/CTestProvider.cs
  test/AElf.Core.Tests/Providers/ITestProvider.cs
  test/AElf.Core.Tests/RegistrationTests.cs
  test/AElf.Kernel.BlockTransactionLimitController.Tests/TestModule.cs
  test/AElf.Kernel.SmartContract.ExecutionPluginForAcs1.Tests/ExecutionPluginForAcs1TestModule.cs
Labels: review

#1902 Improve cross chain module based on sync flag.
  protobuf/crosschain_rpc.proto
  src/AElf.CrossChain.Communication.Grpc/AElf.CrossChain.Communication.Grpc.csproj
  src/AElf.CrossChain.Communication.Grpc/Client/GrpcCrossChainClient.cs
  src/AElf.CrossChain.Communication.Grpc/Client/GrpcCrossChainClientProvider.cs
  src/AElf.CrossChain.Communication.Grpc/Client/GrpcCrossChainClientService.cs
  src/AElf.CrossChain.Communication.Grpc/GrpcCrossChainClientNodePlugin.cs
  src/AElf.CrossChain.Communication.Grpc/Server/GrpcBasicServerBase.cs
  src/AElf.CrossChain.Communication.Grpc/Server/GrpcParentChainServerBase.cs
  src/AElf.CrossChain.Communication.Grpc/Server/GrpcSideChainServerBase.cs
  src/AElf.CrossChain.Communication/Application/CrossChainRequestService.cs
  src/AElf.CrossChain.Communication/Application/CrossChainResponseService.cs
  src/AElf.CrossChain.Communication/Application/ICrossChainClientService.cs
  src/AElf.CrossChain.Communication/Application/ICrossChainRequestService.cs
  src/AElf.CrossChain.Communication/CrossChainClientDto.cs
  src/AElf.CrossChain.Communication/CrossChainCommunicationEventHandler.cs
  src/AElf.CrossChain.Communication/CrossChainPlugin.cs
  src/AElf.CrossChain.Communication/ICrossChainClientProvider.cs
  src/AElf.CrossChain.Communication/Infrastructure/ICrossChainClientProvider.cs
  src/AElf.CrossChain.Core/CrossChainConfigOptions.cs
  src/AElf.CrossChain.Core/CrossChainModuleEventHandler.cs
  src/AElf.CrossChain.Core/IIrreversibleBlockStateProvider.cs
  src/AElf.CrossChain.Core/IrreversibleBlockStateProvider.cs
  src/AElf.CrossChain.Core/LocalLibExtension.cs
  src/AElf.CrossChain.Core/Services/CrossChainDataProvider.cs
  src/AElf.CrossChain.Core/Services/CrossChainValidationProvider.cs
  src/AElf.Kernel.Core/Blockchain/Domain/IChainManager.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.OS.Network.Grpc/GrpcPeer.cs
  test/AElf.CrossChain.Communication.Grpc.Tests/GrpcClientTests.cs
  test/AElf.CrossChain.Communication.Grpc.Tests/GrpcServerTests.cs
  test/AElf.CrossChain.Tests/CrossChainTestBase.cs
  test/AElf.CrossChain.Tests/CrossChainValidationProviderTest.cs
Labels: Approved

#1901 Fix failing to find registration from zero contract error for group transaction
  src/AElf.Kernel.SmartContract.Parallel/ITransactionGrouper.cs
  src/AElf.Kernel.SmartContract.Parallel/LocalParallelTransactionExecutingService.cs
  src/AElf.Kernel.SmartContract.Parallel/TransactionGrouper.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/TransactionGrouperTest.cs
Labels: Approved, review

#1912 Rename TransactionHash to TransactionId.
  bench/AElf.Benchmark/BlockAttachTests.cs
  bench/AElf.Benchmark/BlockchainStateMergingTests.cs
  bench/AElf.Benchmark/TxHubHandleBestChainFoundTests.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Actions.cs
  protobuf/kernel.proto
  src/AElf.Kernel.Consensus.AEDPoS/Application/IrreversibleBlockDiscoveryService.cs
  src/AElf.Kernel.Core/Blockchain/Application/BlockGenerationService.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  src/AElf.Kernel.Core/Blockchain/Application/NewIrreversibleBlockFoundEventHandler.cs
  src/AElf.Kernel.Core/Blockchain/Domain/TransactionManager.cs
  src/AElf.Kernel.Core/Extensions/BlockBodyExtensions.cs
  src/AElf.Kernel.SmartContract.Parallel/ResourceExtractionService.cs
  src/AElf.Kernel.SmartContract/Application/ISmartContractBridgeService.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  src/AElf.Kernel.Types/Block/Block.cs
  src/AElf.Kernel.Types/Block/BlockBody.cs
  src/AElf.Kernel.Types/Block/IBlockBody.cs
  src/AElf.Kernel/Miner/Application/LogEventListeningService.cs
  src/AElf.OS.Core/Network/Extensions/BlockWithTransactionsExtensions.cs
  src/AElf.OS.Core/Network/Extensions/BlockchainServiceExtensions.cs
  src/AElf.OS.Core/Network/Types/BlockWithTransactions.cs
  src/AElf.OS.Rpc.ChainController/ChainControllerRpcService.cs
  src/AElf.OS.Rpc.ChainController/ServiceExtensions.cs
  src/AElf.Types/IBlockBase.cs
  src/AElf.Types/Types/Transaction.cs
  src/AElf.WebApp.Application.Chain/BlockChainAppService.cs
  src/AElf.WebApp.Application.Chain/TransactionResultAppService.cs
  test/AElf.Contracts.CrossChain.Tests/CrossChainIndexingActionTest.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/BlockValidationProviderTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/TransactionResultServiceTests.cs
  test/AElf.Kernel.SmartContractExecution.Akka.Tests/Execution/MockSetup.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutingServiceTests.cs
  test/AElf.Kernel.Tests/TestBlockExecutingService.cs
  test/AElf.Kernel.Types.Tests/Block/BlockTests.cs
  test/AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs
  test/AElf.Sdk.CSharp.Tests/SerializationHelperTests.cs
  test/AElf.WebApp.Application.Chain.Tests/BlockChainAppServiceTest.cs
Labels: review

#1886 broadcast block stream
  protobuf/peer_service.proto
  src/AElf.OS.Core/CoreOSAElfModule.cs
  src/AElf.OS.Core/Network/Application/INetworkService.cs
  src/AElf.OS.Core/Network/Application/NetworkService.cs
  src/AElf.OS.Core/Network/Events/BlockReceivedEvent.cs
  src/AElf.OS.Core/Network/Infrastructure/IPeer.cs
  src/AElf.OS.Core/Network/NetworkConstants.cs
  src/AElf.OS.Network.Grpc/GrpcPeer.cs
  src/AElf.OS.Network.Grpc/GrpcServerService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncValidationService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncValidationService.cs
  src/AElf.OS/BlockSync/BlockSyncConstants.cs
  src/AElf.OS/BlockSync/Dto/SyncAnnouncementDto.cs
  src/AElf.OS/BlockSync/Dto/SyncBlockDto.cs
  src/AElf.OS/Handlers/AnnouncementReceivedEventHandler.cs
  src/AElf.OS/Handlers/BlockMinedEventHandler.cs
  src/AElf.OS/Handlers/BlockReceivedEventHandler.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncServiceTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncValidationServiceTests.cs
Labels: Approved, review

#1911 Improve block sync efficiency
  src/AElf.OS.Core/Network/NetworkConstants.cs
  src/AElf.OS.Core/Network/NetworkOptions.cs
  src/AElf.OS/BlockSync/Application/BlockDownloadService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncAttachService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncQueueService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncService.cs
  src/AElf.OS/BlockSync/Application/BlockSyncValidationService.cs
  src/AElf.OS/BlockSync/Application/IBlockDownloadService.cs
  src/AElf.OS/BlockSync/Application/IBlockSyncAttachService.cs
  src/AElf.OS/BlockSync/BlockSyncConstants.cs
  src/AElf.OS/BlockSync/BlockSyncOptions.cs
  src/AElf.OS/BlockSync/Domain/BlockDownloadJobManager.cs
  src/AElf.OS/BlockSync/Domain/IBlockDownloadJobManager.cs
  src/AElf.OS/BlockSync/Dto/DownloadBlockDto.cs
  src/AElf.OS/BlockSync/Infrastructure/BlockSyncStateProvider.cs
  src/AElf.OS/BlockSync/Infrastructure/IBlockDownloadJobStore.cs
  src/AElf.OS/BlockSync/Infrastructure/IBlockSyncStateProvider.cs
  src/AElf.OS/BlockSync/Infrastructure/InMemoryBlockDownloadJobStore.cs
  src/AElf.OS/BlockSync/Types/BlockDownloadJobInfo.cs
  src/AElf.OS/BlockSync/Types/DownloadBlocksResult.cs
  src/AElf.OS/BlockSync/Worker/BlockDownloadWorker.cs
  src/AElf.OS/Handlers/AnnouncementReceivedEventHandler.cs
  src/AElf.OS/Handlers/BlockReceivedEventHandler.cs
  src/AElf.OS/OSAElfModule.cs
  src/AElf.OS/OSConstants.cs
  test/AElf.OS.Tests/BlockDownloadWorkerTestAElfModule.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockDownloadServiceTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncServiceForkedTests.cs
  test/AElf.OS.Tests/BlockSync/Application/BlockSyncServiceTests.cs
  test/AElf.OS.Tests/BlockSync/Worker/BlockDownloadWorkerForkedTests.cs
  test/AElf.OS.Tests/BlockSync/Worker/BlockDownloadWorkerManyJobTests.cs
  test/AElf.OS.Tests/BlockSync/Worker/BlockDownloadWorkerTests.cs
  test/AElf.OS.Tests/OSTestBase.cs
Labels: review

#1788 Consensus lib double confirm
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_HelpMethods_GetInformationToUpdateConsensus.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_LIB.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_NextTerm.cs
  contract/AElf.Contracts.Consensus.AEDPoS/Types/Round_ExtractInformationToUpdateConsensus.cs
  contract/AElf.Contracts.Consensus.AEDPoS/Types/Round_GetLogs.cs
  contract/AElf.Contracts.Consensus.AEDPoS/Types/Round_ImpliedIrreversibleBlockHeight.cs
  protobuf/aedpos_contract.proto
  src/AElf.Kernel.Consensus.AEDPoS/Application/IrreversibleBlockDiscoveryService.cs
  src/AElf.Kernel.Core/SmartContract/Infrastructure/StateStore.cs
Labels: Approved

#1860 Feature mark conflicting executions
  AElf.sln
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_HelpMethods_GetConsensusCommand.cs
  contract/AElf.Contracts.MultiToken/TokenContract_ACS2_StatePathsProvider.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Actions.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Helper.cs
  contract/AElf.Contracts.Profit/ProfitContract.cs
  protobuf/acs2.proto
  protobuf/parallel_execution.proto
  protobuf/test_basic_function_with_parallel_contract.proto
  src/AElf.Kernel.SmartContract.Parallel/Application/ConflictingTransactionsFoundInParallelGroupsEventHandler.cs
  src/AElf.Kernel.SmartContract.Parallel/Application/LocalParallelTransactionExecutingService.cs
  src/AElf.Kernel.SmartContract.Parallel/Application/ParallelExecutionInterestedEventsHandler.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/CodeRemarksManager.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/CodeRemarksService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ConflictingTransactionIdentificationService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ConflictingTransactionsFoundInParallelGroupsEvent.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ExecutiveExtensions.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ICodeRemarksManager.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ICodeRemarksService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/IConflictingTransactionIdentificationService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/IResourceExtractionService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ITransactionGrouper.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ResourceExtractionService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/TransactionGrouper.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/UnionFindNode.cs
  src/AElf.Sdk.CSharp/State/MappedState.cs
  src/AElf.Sdk.CSharp/State/SingletonState`.cs
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/AElf.Contracts.TestContract.BasicFunctionWithParallel.csproj
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/BasicFunctionWithParallelContractState.cs
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/BasicFunctionWithParallelContract_ACS2_StatePathsProvider.cs
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/BasicFunctionWithParallelContract_Action.cs
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/BasicFunctionWithParallelContract_View.cs
  test/AElf.Contracts.TestContract.BasicFunctionWithParallel/ContractReference.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/AElf.Kernel.SmartContract.Parallel.Tests.csproj
  test/AElf.Kernel.SmartContract.Parallel.Tests/ConflictingTransactionIdentificationServiceTest.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/MockBlockchainService.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/MockCodeRemarksManager.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/MockResourceExtractionService.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/ResourceExtractionServiceTest.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/TestModule.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/TransactionGrouperTest.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
  test/AElf.Parallel.Tests/AElf.Parallel.Tests.csproj
  test/AElf.Parallel.Tests/ParallelTestAElfModule.cs
  test/AElf.Parallel.Tests/ParallelTestHelper.cs
  test/AElf.Parallel.Tests/ParallelTests.cs
Labels: Approved, review
