Repository AElfProject/AElf, pull requests merged in 2020-04, with the labels that each got.

#2640 add block executed set to BlockAcceptedEventData & BestChainFoundEven…
  bench/AElf.Benchmark/BlockchainStateMergingTests.cs
  bench/AElf.Benchmark/TxHubHandleBestChainFoundTests.cs
  src/AElf.Kernel.Core/Blockchain/BlockExecutedSet.cs
  src/AElf.Kernel.Core/Blockchain/Events/BestChainFoundEventData.cs
  src/AElf.Kernel.Core/Blockchain/Events/BlockAcceptedEvent.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.Kernel.SmartContractExecution/Application/IBlockExecutingService.cs
  src/AElf.Kernel/Miner/Application/BestChainFoundEventHandlerForLogEventListening.cs
  src/AElf.Kernel/Miner/Application/IMinerService.cs
  src/AElf.Kernel/Miner/Application/IMiningService.cs
  src/AElf.Kernel/Miner/Application/MinerService.cs
  src/AElf.Kernel/Miner/Application/MiningService.cs
  test/AElf.Contracts.TestBase/ContractTester.cs
  test/AElf.Kernel.SmartContractExecution.Tests/SmartContractExecutionExecutingTestAElfModule.cs
  test/AElf.Kernel.Tests/TestBlockExecutingService.cs
  test/AElf.Kernel.TransactionPool.Tests/Infrastructure/TxHubTests.cs
Labels: regression test, stability test

#2601 Adjust events fire.
  src/AElf.CrossChain.Core/CrossChainAElfModule.cs
  src/AElf.CrossChain.Core/Indexing/Application/CrossChainIndexingDataProposedLogEventProcessor.cs
  src/AElf.Kernel.CodeCheck/CodeCheckAElfModule.cs
  src/AElf.Kernel.CodeCheck/CodeCheckRequiredLogEventProcessor.cs
  src/AElf.Kernel.Consensus.AEDPoS/AEDPoSAElfModule.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/IrreversibleBlockFoundLogEventProcessor.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/IrreversibleBlockHeightUnacceptableLogEventProcessor.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/SecretSharingInformationLogEventProcessor.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  src/AElf.Kernel.Core/Blockchain/Events/BestChainFoundEventData.cs
  src/AElf.Kernel.Core/SmartContract/Application/ILogEventProcessor.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.Kernel.SmartContractExecution/Events/BlocksExecutionSucceededEvent.cs
  src/AElf.Kernel/Miner/Application/BestChainFoundEventHandlerForLogEventListening.cs
  src/AElf.Kernel/Miner/Application/BlocksExecutionSucceededEventHandlerForLogEventListening.cs
Labels: stability

#2590 Add timeout and threshold in contract auditor, clean up unnecessary codes
  src/AElf.CSharp.CodeOps/CSharpCodeOpsAElfModule.cs
  src/AElf.CSharp.CodeOps/CSharpCodeOpsOptions.cs
  src/AElf.CSharp.CodeOps/CSharpContractAuditor.cs
  src/AElf.CSharp.CodeOps/Constants.cs
  src/AElf.CSharp.CodeOps/Exceptions.cs
  src/AElf.CSharp.CodeOps/Extensions.cs
  src/AElf.CSharp.CodeOps/Patchers/Module/ResetFieldsMethodInjector.cs
  src/AElf.CSharp.CodeOps/Policies/PrivilegePolicy.cs
  src/AElf.CSharp.CodeOps/Validators/IValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/ArrayValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/DescriptorAccessValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/FloatOpsValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/GetHashCodeValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/MultiDimArrayValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Method/UncheckedMathValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Module/ContractStructureValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Module/ObserverProxyValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Module/ResetFieldsValidator.cs
  src/AElf.CSharp.CodeOps/Validators/Whitelist/Whitelist.cs
  src/AElf.Contracts.Deployer/Program.cs
  src/AElf.Runtime.CSharp/CSharpSmartContractRunner.cs
  src/AElf.Runtime.CSharp/CSharpSmartContractRuntimeException.cs
  src/AElf.Runtime.CSharp/Executive.cs
  test/AElf.CSharp.CodeOps.Tests/ContractAuditorTests.cs
  test/AElf.CSharp.CodeOps.Tests/ContractPolicyTests.cs
  test/AElf.CSharp.CodeOps.Tests/TestCSharpCodeOpsAElfModule.cs
  test/AElf.Contracts.TestContract.Tests/TestContractTestBase.cs
Labels: regression

#2585 Fix issues
  src/AElf.Kernel.ChainController/Application/ChainCreationService.cs
  src/AElf.Kernel.Core/Blockchain/Application/ChainBlockLinkService.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockchainService.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockExecutionResult.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockExecutionResultProcessingService.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockchainExecutingService.cs
  src/AElf.Kernel.SmartContractExecution/Application/IBlockAttachService.cs
  src/AElf.Kernel.SmartContractExecution/Application/IBlockExecutionResultProcessingService.cs
  src/AElf.Kernel.SmartContractExecution/Application/IBlockchainExecutingService.cs
  src/AElf.Kernel.SmartContractExecution/Extensions/BlockchainServiceExtensions.cs
  test/AElf.Contracts.TestBase/ContractTester.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/FullBlockchainServiceTests.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/MockBlockchainService.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutionResultProcessingServiceTests.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/FullBlockchainExecutingServiceExecuteFailedTests.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/FullBlockchainExecutingServiceTests.cs
  test/AElf.Kernel.SmartContractExecution.Tests/Application/FullBlockchainExecutingServiceValidateFailedTests.cs
Labels: regression, stability

#2587 Improve network
  src/AElf.OS.Core/Network/Application/INetworkService.cs
  src/AElf.OS.Core/Network/Application/ISyncStateService.cs
  src/AElf.OS.Core/Network/Application/NetworkService.cs
  src/AElf.OS.Core/Network/Application/PeerDiscoveryService.cs
  src/AElf.OS.Core/Network/Infrastructure/IBlackListedPeerProvider.cs
  src/AElf.OS.Core/Network/NetworkConstants.cs
  src/AElf.OS.Core/Network/NetworkOptions.cs
  src/AElf.OS.Core/Network/Protocol/Types/PeerConnectionInfo.cs
  src/AElf.OS.Core/Network/Types/AElfPeerEndpoint.cs
  src/AElf.OS.Core/Network/Types/PeerInfo.cs
  src/AElf.OS.Network.Grpc/Connection/IPeerDialer.cs
  src/AElf.OS.Network.Grpc/Connection/PeerDialer.cs
  src/AElf.OS.Network.Grpc/GrpcClient.cs
  src/AElf.OS.Network.Grpc/GrpcNetworkServer.cs
  src/AElf.OS.Network.Grpc/Helpers/TlsHelper.cs
  src/AElf.OS/Handlers/AbnormalPeerEventHandler.cs
  src/AElf.WebApp.Application.Net/NetAppService.cs
  test/AElf.OS.Core.Tests/Network/Infrastructure/BlackListProviderTests.cs
  test/AElf.OS.Core.Tests/Network/Infrastructure/NetworkInfrastructureTestModule.cs
  test/AElf.OS.Core.Tests/Network/Infrastructure/PeerPoolTests.cs
  test/AElf.OS.Core.Tests/Network/Service/NetworkServiceTestModule.cs
  test/AElf.OS.Core.Tests/Network/Service/NetworkServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Service/PeerDiscoveryServiceTests.cs
  test/AElf.OS.Core.Tests/Network/SyncStateServiceTests.cs
  test/AElf.OS.Core.Tests/OSCoreSyncFlagTestModule.cs
  test/AElf.OS.Tests/BlockSync/BlockSyncAbnormalPeerTestAElfModule.cs
  test/AElf.OS.Tests/BlockSync/BlockSyncAttachBlockAbnormalPeerTestAElfModule.cs
Labels: functional, regression, stability

#2524 Add timeout for TCP connect.
  src/AElf.OS.Core/Network/Application/PeerDiscoveryService.cs
  src/AElf.OS.Network.Grpc/Connection/ConnectionService.cs
  src/AElf.OS.Network.Grpc/Connection/PeerDialer.cs
  src/AElf.OS.Network.Grpc/GrpcNetworkServer.cs
  src/AElf.OS.Network.Grpc/Service/GrpcServerService.cs
Labels: stability

#2592 add transaction execution test in transaction pool
  bench/AElf.Benchmark/BenchmarkAElfModule.cs
  bench/AElf.Benchmark/BenchmarkTestBase.cs
  bench/AElf.Benchmark/MiningTxHubBenchmark.cs
  bench/AElf.Benchmark/TxHubHandleBestChainFoundTests.cs
  bench/AElf.Benchmark/TxHubTransactionsReceiveTests.cs
  src/AElf.CSharp.CodeOps/Constants.cs
  src/AElf.Contracts.TestKit/MockTxHub.cs
  src/AElf.Kernel.SmartContract.Parallel/Application/ParallelExecutionInterestedEventsHandler.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/IResourceExtractionService.cs
  src/AElf.Kernel.SmartContract.Parallel/Domain/ResourceExtractionService.cs
  src/AElf.Kernel.SmartContract/Extensions/TaskExtensions.cs
  src/AElf.Kernel.TransactionPool/Application/ITransactionPoolService.cs
  src/AElf.Kernel.TransactionPool/Application/TransactionToAddressValidationProvider.cs
  src/AElf.Kernel.TransactionPool/Events/TransactionAcceptedEvent.cs
  src/AElf.Kernel.TransactionPool/Events/TransactionExecutionValidationFailedEvent.cs
  src/AElf.Kernel.TransactionPool/Events/TransactionsReceivedEvent.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/BasicTransactionValidationProvider.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/ITxHub.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/TransactionExecutionValidationProvider.cs
  src/AElf.Kernel.TransactionPool/Infrastructure/TxHub.cs
  src/AElf.Kernel.TransactionPool/TransactionOptions.cs
  src/AElf.Kernel.TransactionPool/TransactionPoolAElfModule.cs
  src/AElf.Kernel.Types/Transaction/QueuedTransaction.cs
  src/AElf.Kernel/Miner/Application/TxPoolInterestedEventsHandler.cs
  src/AElf.OS.Network.Grpc/Connection/PeerDialer.cs
  src/AElf.OS.Network.Grpc/Service/GrpcServerService.cs
  src/AElf.OS/Handlers/Network/TransactionAcceptedEventHandler.cs
  src/AElf.WebApp.Application.Chain/TransactionAppService.cs
  test/AElf.Contracts.Economic.TestBase/EconomicTestTransactionExecutor.cs
  test/AElf.Contracts.TestBase/ContractTester.cs
  test/AElf.Contracts.TestBase/MockTxHub.cs
  test/AElf.Kernel.SmartContract.Parallel.Tests/MockResourceExtractionService.cs
  test/AElf.Kernel.TransactionPool.Tests/Infrastructure/TransactionExecutionValidationProviderTests.cs
  test/AElf.Kernel.TransactionPool.Tests/Infrastructure/TxHubTests.cs
  test/AElf.Kernel.TransactionPool.Tests/TransactionMockExecutionHelper.cs
  test/AElf.Kernel.TransactionPool.Tests/TransactionPoolTestAElfModule.cs
  test/AElf.OS.Network.Grpc.Tests/GrpcServerServiceTests.cs
  test/AElf.OS.TestBase/MockTxHub.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
  test/AElf.WebApp.Application.TestBase/WebAppTestAElfModule.cs
Labels: functional, regression, stability

#2651 Enable Controller To Customize Dividend Pool Weight
  contract/AElf.Contracts.Treasury/TreasuryContract.cs
  contract/AElf.Contracts.Treasury/TreasuryContractConstants.cs
  contract/AElf.Contracts.Treasury/TreasuryContractState.cs
  protobuf/treasury_contract.proto
  test/AElf.Contracts.EconomicSystem.Tests/BVT/AdvanceResourceTokenTests.cs
  test/AElf.Contracts.EconomicSystem.Tests/BVT/TransactionFeeTests.cs
  test/AElf.Contracts.EconomicSystem.Tests/BVT/TreasureViewTests.cs
  test/AElf.Contracts.EconomicSystem.Tests/BVT/TreasuryBasicTests.cs
Labels: compatibility, functional, stability

#2652 Improve contract reader factory
  src/AElf.Blockchains.SideChain/SideChainPrimaryTokenSymbolProvider.cs
  src/AElf.Blockchains.SideChain/TokenContractReaderFactory.cs
  src/AElf.CrossChain.Core/CrossChainService.cs
  src/AElf.CrossChain.Core/Indexing/Application/CrossChainIndexingDataService.cs
  src/AElf.CrossChain.Core/Indexing/Application/CrossChainIndexingDataValidationService.cs
  src/AElf.CrossChain.Core/Reader/MethodStubFactory.cs
  src/AElf.CrossChain.Core/Reader/ReaderFactory.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/AEDPoSInformationProvider.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/ReaderFactory.cs
  src/AElf.Kernel.Consensus.Core/Application/ConsensusService.cs
  src/AElf.Kernel.Consensus.Core/Application/IConsensusReaderContextService.cs
  src/AElf.Kernel.Consensus.Core/Application/MethodStubFactory.cs
  src/AElf.Kernel.Consensus.Core/Application/ReaderFactory.cs
  src/AElf.Kernel.Proposal/Application/ProposalService.cs
  src/AElf.Kernel.Proposal/Infrastructure/ContractReaderFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForCallThreshold/AssemblyInfo.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForCallThreshold/CheckThresholdExecutionPlugin.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForCallThreshold/MethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForCallThreshold/TransactionGeneratingOnlyMethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/ClaimTransactionFeesValidationProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/FeeChargePreExecutionPlugin.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/MethodFeeAffordableValidationProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/MethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/TokenContractMethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/TokenContractReaderFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/TokenReadFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/TransactionGeneratingOnlyMethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/DonateResourceTokenValidationProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/MethodStubFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/ResourceConsumptionPostExecutionPlugin.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/ResourceConsumptionPreExecutionPlugin.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/TokenReadFactory.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/TransactionGeneratingOnlyMethodStubFactory.cs
  src/AElf.Kernel.SmartContract/Application/ContractReaderContext.cs
  src/AElf.Kernel.SmartContract/Application/ContractReaderFactory.cs
  src/AElf.Kernel.SmartContract/Application/IContractReaderFactory.cs
  src/AElf.Kernel.SmartContract/Application/ReadOnlyMethodStubFactory.cs
  src/AElf.Kernel.SmartContract/SmartContractAElfModule.cs
  src/AElf.Kernel.TransactionPool/Application/ZeroContractMethodStubFactory.cs
  src/AElf.Kernel.TransactionPool/Application/ZeroContractReaderFactory.cs
  test/AElf.CrossChain.Tests/CrossChainTestModule.cs
  test/AElf.Kernel.Consensus.AEDPoS.Tests/AEDPoSTestAElfModule.cs
  test/AElf.Kernel.Consensus.Tests/ConsensusTestAElfModule.cs
  test/AElf.Parallel.Tests/ParallelTestAElfModule.cs
Labels: regression, stability

#2637 Network layer process transaction validation failed
  src/AElf.OS.Core/Network/Application/IPeerInvalidTransactionProcessingService.cs
  src/AElf.OS.Core/Network/Application/NetworkService.cs
  src/AElf.OS.Core/Network/Application/PeerInvalidTransactionProcessingService.cs
  src/AElf.OS.Core/Network/Infrastructure/IPeerInvalidTransactionProvider.cs
  src/AElf.OS.Core/Network/NetworkConstants.cs
  src/AElf.OS.Core/Network/NetworkOptions.cs
  src/AElf.OS.Network.Grpc/AElf.OS.Network.Grpc.csproj
  src/AElf.OS.Network.Grpc/Service/GrpcServerService.cs
  src/AElf.OS/Handlers/TransactionExecutionValidationFailedEventHandler.cs
  test/AElf.OS.Core.Tests/Network/Application/NetworkServicePropagationTest.cs
  test/AElf.OS.Core.Tests/Network/Application/NetworkServiceTestModule.cs
  test/AElf.OS.Core.Tests/Network/Application/NetworkServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Application/PeerDiscoveryServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Application/PeerInvalidTransactionProcessingServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Application/PeerReconnectionServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Application/SyncStateServiceTests.cs
  test/AElf.OS.Core.Tests/Network/Infrastructure/PeerInvalidTransactionProviderTests.cs
  test/AElf.OS.Core.Tests/Network/PeerInvalidTransactionTestModule.cs
  test/AElf.OS.Core.Tests/OSCoreTestAElfModule.cs
  test/AElf.OS.Core.Tests/OSCoreTestBase.cs
Labels: functional, stability

#2706 Use map to store block header extra data
  protobuf/kernel.proto
  src/AElf.CrossChain.Core/Application/CrossChainResponseService.cs
  src/AElf.CrossChain.Core/CrossChainConstants.cs
  src/AElf.CrossChain.Core/CrossChainCoreModule.cs
  src/AElf.CrossChain/Application/CrossChainBlockExtraDataProvider.cs
  src/AElf.CrossChain/Application/CrossChainValidationProvider.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/AEDPoSBroadcastPrivilegedPubkeyListProvider.cs
  src/AElf.Kernel.Consensus.AEDPoS/Application/AEDPoSExtraDataExtractor.cs
  src/AElf.Kernel.Consensus.Core/Application/ConsensusExtraDataProvider.cs
  src/AElf.Kernel.Consensus.Core/Application/IConsensusExtraDataKeyProvider.cs
  src/AElf.Kernel.Consensus.Core/ConsensusConstants.cs
  src/AElf.Kernel.Consensus.Core/CoreConsensusAElfModule.cs
  src/AElf.Kernel.Core/Blockchain/Application/BlockExtraDataService.cs
  src/AElf.Kernel.Core/Blockchain/Application/BlockGenerationService.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockExtraDataProvider.cs
  src/AElf.Kernel.Core/Blockchain/Application/IBlockExtraDataService.cs
  test/AElf.CrossChain.Core.Tests/CrossChainCommunicationTestModule.cs
  test/AElf.CrossChain.Tests/CrossChainBlockExtraDataProviderTests.cs
  test/AElf.CrossChain.Tests/CrossChainValidationProviderTests.cs
  test/AElf.Kernel.Consensus.AEDPoS.Tests/Application/ConsensusExtraDataProviderTests.cs
  test/AElf.Kernel.Consensus.Tests/Application/ConsensusValidationProviderTests.cs
  test/AElf.Kernel.Core.Tests/Blockchain/Application/BlockExtraDataServiceTests.cs
  test/AElf.Kernel.Core.Tests/KernelCoreTestAElfModule.cs
  test/AElf.Kernel.TestBase/KernelTestHelper.cs
  test/AElf.Kernel.Tests/KernelTestAElfModule.cs
  test/AElf.Kernel.Types.Tests/Block/BlockTests.cs
  test/AElf.OS.Core.Tests/Helpers/OsCoreTestHelper.cs
  test/AElf.OS.Core.Tests/OSCoreWithChainTestAElfModule.cs
  test/AElf.OS.Network.Grpc.Tests/Helpers/NetworkTestHelper.cs
  test/AElf.OS.TestBase/OSTestHelper.cs
Labels: regression, stability

#2710 Replace context transactionId.
  contract/AElf.Contracts.Association/Association.cs
  contract/AElf.Contracts.Association/Association_Helper.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_ACS6_RandomNumberProvider.cs
  contract/AElf.Contracts.Consensus.AEDPoS/AEDPoSContract_GetConsensusBlockExtraData.cs
  contract/AElf.Contracts.Consensus.AEDPoS/ConsensusHeaderInfoValidationProviders/UpdateValueValidationProvider.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  contract/AElf.Contracts.Election/ElectionContract_Candidate.cs
  contract/AElf.Contracts.Election/ElectionContract_Elector.cs
  contract/AElf.Contracts.Election/ElectionContract_Maintainence.cs
  contract/AElf.Contracts.Genesis/BasicContractZero_Helper.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Fees.cs
  contract/AElf.Contracts.Parliament/Parliament.cs
  contract/AElf.Contracts.Parliament/Parliament_Helper.cs
  contract/AElf.Contracts.Profit/ProfitContract.cs
  contract/AElf.Contracts.Referendum/Referendum.cs
  contract/AElf.Contracts.Referendum/Referendum_Helper.cs
  contract/AElf.Contracts.TokenHolder/TokenHolderContract.cs
  contract/AElf.Contracts.Vote/VoteContract.cs
  contract/AElf.Contracts.Vote/VoteContractState.cs
  contract/AElf.Contracts.Vote/VoteExtensions.cs
  protobuf/acs3.proto
  protobuf/cross_chain_contract.proto
  protobuf/election_contract.proto
  protobuf/profit_contract.proto
  src/AElf.Kernel.SmartContract.ExecutionPluginForMethodFee/ClaimTransactionFeesValidationProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/DonateResourceTokenValidationProvider.cs
  src/AElf.Kernel.SmartContract.Shared/ISmartContractBridgeContext.cs
  src/AElf.Kernel.SmartContract.Shared/ITransactionContext.cs
  src/AElf.Kernel.SmartContract/Application/PlainTransactionExecutingService.cs
  src/AElf.Kernel.SmartContract/Dto/SingleTransactionExecutingDto.cs
  src/AElf.Kernel.SmartContract/HostSmartContractBridgeContext.cs
  src/AElf.Kernel.SmartContract/TransactionContext.cs
  src/AElf.OS.Core/Network/Protocol/HandshakeProvider.cs
  src/AElf.Sdk.CSharp/CSharpSmartContractContext.cs
  src/AElf.Types/Helper/HashHelper.cs
  test/AElf.Contracts.AEDPoSExtension.Demo.Tests/RandomNumberGenerateTests.cs
  test/AElf.Contracts.Association.Tests/AssociationContractTests.cs
  test/AElf.Contracts.Consensus.AEDPoS.Tests/BVT/MiningProcessTest.cs
  test/AElf.Contracts.EconomicSystem.Tests/BVT/TransactionFeeTests.cs
  test/AElf.Contracts.Election.Tests/BVT/ElectionTests.cs
  test/AElf.Contracts.Parliament.Tests/ParliamentContractTest.cs
  test/AElf.Contracts.Referendum.Tests/ReferendumContractTest.cs
  test/AElf.Contracts.TestContract.CommitmentScheme/CommitmentSchemeContract.cs
  test/AElf.Contracts.TestContract.Events/Events_Helper.cs
  test/AElf.Contracts.Vote.Tests/VoteContractTestHelper.cs
  test/AElf.Kernel.SmartContract.Tests/HostSmartContractBridgeContextTests.cs
  test/AElf.OS.Core.Tests/Network/Protocol/HandshakeProviderTests.cs
  test/AElf.OS.Network.Grpc.Tests/Helpers/NetworkTestHelper.cs
Labels: regression, stability

#2707 Fix network broadcast problem
  src/AElf.OS.Core/Network/Application/NetworkService.cs
  test/AElf.OS.Core.Tests/Network/Application/NetworkServicePropagationTest.cs
  test/AElf.OS.Core.Tests/Network/Application/NetworkServiceTestModule.cs
Labels: functional

#2629 Fix the timeout of known block
  src/AElf.OS.Network.Grpc/GrpcPeer.cs
Labels: functional

#2736 [WIP] Indexing fee adjustment authority.
  contract/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  contract/AElf.Contracts.CrossChain/CrossChainContract.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract_View.cs
  contract/AElf.Contracts.CrossChain/CrossChainReferenceState.cs
  contract/AElf.Contracts.MultiToken/AElf.Contracts.MultiToken.csproj
  contract/AElf.Contracts.MultiToken/TokenContractState.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Helper.cs
  protobuf/cross_chain_contract.proto
  test/AElf.Contracts.CrossChain.Tests/SideChainLifeTimeManagementTest.cs
Labels: functional

#2716 Fix few bugs.
  contract/AElf.Contracts.Association/Association.cs
  contract/AElf.Contracts.Association/AssociationState.cs
  contract/AElf.Contracts.Association/Association_Helper.cs
  contract/AElf.Contracts.CrossChain/AElf.Contracts.CrossChain.csproj
  contract/AElf.Contracts.CrossChain/CrossChainContract.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract_Helper.cs
  contract/AElf.Contracts.CrossChain/CrossChainContract_View.cs
  contract/AElf.Contracts.CrossChain/CrossChainReferenceState.cs
  contract/AElf.Contracts.MultiToken/AElf.Contracts.MultiToken.csproj
  contract/AElf.Contracts.MultiToken/TokenContractState.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Helper.cs
  contract/AElf.Contracts.Parliament/Parliament.cs
  contract/AElf.Contracts.Parliament/ParliamentState.cs
  contract/AElf.Contracts.Parliament/Parliament_Helper.cs
  contract/AElf.Contracts.Referendum/Referendum.cs
  contract/AElf.Contracts.Referendum/ReferendumState.cs
  contract/AElf.Contracts.Referendum/Referendum_Helper.cs
  protobuf/configuration_contract.proto
  protobuf/cross_chain_contract.proto
  src/AElf.Kernel.SmartContract.Parallel/Application/BlockParallelExecutingService.cs
  src/AElf.Kernel.SmartContract/Domain/ReturnSetCollection.cs
  src/AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs
  src/AElf.Kernel/ConsensusRequestMiningEventHandler.cs
  src/AElf.Kernel/Miner/Application/IMiningRequestService.cs
  test/AElf.Contracts.CrossChain.Tests/SideChainLifeTimeManagementTest.cs
Labels: regression, stability

#2733 Fix SDK dependency
  src/AElf.Kernel.SmartContract.Shared/AElf.Kernel.SmartContract.Shared.csproj
  src/AElf.Kernel.SmartContract.Shared/IStateProvider.cs
  src/AElf.Kernel.SmartContract/ICachedStateProvider.cs
  src/AElf.Kernel.SmartContract/IScopedStateProvider.cs
  src/AElf.Kernel.SmartContract/ITransactionContext.cs
Labels: regression

#2734 Remove unnecessary refs in contract projects.
  contract/AElf.Contracts.Configuration/AElf.Contracts.Configuration.csproj
  contract/AElf.Contracts.Consensus.AEDPoS/AElf.Contracts.Consensus.AEDPoS.csproj
  contract/AElf.Contracts.Economic/AElf.Contracts.Economic.csproj
  contract/AElf.Contracts.Economic/EconomicContractState.cs
  contract/AElf.Contracts.Election/AElf.Contracts.Election.csproj
  contract/AElf.Contracts.Election/ElectionContractReferenceState.cs
  contract/AElf.Contracts.MultiToken/AElf.Contracts.MultiToken.csproj
  contract/AElf.Contracts.MultiToken/TokenContractReferenceState.cs
  contract/AElf.Contracts.MultiToken/TokenContractState.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Actions.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Helper.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Views.cs
  contract/AElf.Contracts.Parliament/AElf.Contracts.Parliament.csproj
  contract/AElf.Contracts.Profit/AElf.Contracts.Profit.csproj
  contract/AElf.Contracts.Referendum/AElf.Contracts.Referendum.csproj
  contract/AElf.Contracts.Referendum/ReferendumState.cs
  contract/AElf.Contracts.TokenConverter/AElf.Contracts.TokenConverter.csproj
  contract/AElf.Contracts.TokenConverter/TokenConverterContractState.cs
  contract/AElf.Contracts.TokenHolder/AElf.Contracts.TokenHolder.csproj
  contract/AElf.Contracts.Treasury/AElf.Contracts.Treasury.csproj
  contract/AElf.Contracts.Vote/AElf.Contracts.Vote.csproj
  protobuf/economic_contract.proto
  protobuf/token_contract.proto
  protobuf/token_contract_impl.proto
  test/AElf.Contracts.MultiToken.Tests/BVT/TokenApplicationTests.cs
  test/AElf.Contracts.TestContract.BasicFunction/AElf.Contracts.TestContract.BasicFunction.csproj
  test/AElf.Contracts.TestContract.DApp/AElf.Contracts.TestContract.DApp.csproj
  test/AElf.Contracts.TokenHolder.Tests/AElf.Contracts.TokenHolder.Tests.csproj
Labels: stability

#2735 Fix ACS8 related transaction and validation logic.
  contract/AElf.Contracts.MultiToken/TokenContract_Fees.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Helper.cs
  protobuf/transaction_fee.proto
  src/AElf.Kernel.Core/SmartContract/Application/LogEventListeningService.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/DonateResourceTokenValidationProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/DonateResourceTransactionGenerator.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/ITotalResourceTokensMapsProvider.cs
  src/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee/ResourceTokenChargedLogEventProcessor.cs
  test/AElf.Contracts.MultiToken.Tests/BVT/TokenApplicationTests.cs
  test/AElf.Contracts.Profit.Tests/ProfitTests.cs
  test/AElf.Contracts.TokenHolder.Tests/AElf.Contracts.TokenHolder.Tests.csproj
  test/AElf.Kernel.SmartContract.ExecutionPluginForResourceFee.Tests/ExecutionPluginForResourceFeeTest.cs
Labels: regression, stability

#2752 Token contract initialize.
  contract/AElf.Contracts.Economic/EconomicContract.cs
  contract/AElf.Contracts.MultiToken/TokenContract_Actions.cs
  protobuf/token_contract.proto
  protobuf/token_contract_impl.proto
  src/AElf.Blockchains.BasicBaseChain/BasicBaseChainAElfModule.cs
  src/AElf.Blockchains.MainChain/MainChainContractDeploymentListProvider.cs
  src/AElf.Blockchains.SideChain/SideChainContractDeploymentListProvider.cs
  src/AElf.ContractTestBase/MainChainContractDeploymentListProvider.cs
  src/AElf.ContractTestBase/SideChainContractDeploymentListProvider.cs
  src/AElf.Kernel.Consensus.Core/Application/ConsensusExtraDataProvider.cs
  src/AElf.Kernel.Core/Miner/Application/SystemTransactionGenerationService.cs
  src/AElf.Kernel.Token/TokenContractInitializationProvider.cs
  test/AElf.Contracts.AEDPoSExtension.Demo.Tests/DonateResourceTokenTest.cs
Labels: regression
